import {Text, Flex, Stack} from '@chakra-ui/react';
import {Button} from 'ui-lib/ui-lib.components';
import {useState} from 'react';
import {OTPInput} from 'chakra-otp-input';
import {MatadorCustomToast} from 'pages/veerge_menu/loop';

export const VerifyUserViaOTP = ({
  initiatePaymentOnSubmit,
  showVerifyComponent,
  setShowVerifyComponent,
  dividendPayloadOnSubmit,
}) => {
  const [code, setCode] = useState('');

  const handleVerifyDividendPayment = () => {
    if (code?.length == 6) {
      initiatePaymentOnSubmit({...dividendPayloadOnSubmit, code: Number(code)});
      setShowVerifyComponent('false');
    } else {
      return toast({
        render: () => <MatadorCustomToast description={'Invalid OTP'} />,
        duration: 4000,
        isClosable: true,
        position: 'bottom-right',
      });
    }
  };
  return (
    <Stack w="350px" fontFamily={'Euclid Circular B'}>
      <Text
        align="left"
        color="#0D0D0D"
        fontSize={'16px'}
        fontWeight={'500'}
      >{`Verify it’s you`}</Text>
      <Text
        mt="12px"
        align="left"
        color="#3D3D3D"
        fontSize={'14px'}
        fontWeight={'400'}
      >{`Enter the 6-digit verification code generated by your Authenticator app to proceed.`}</Text>
      <Flex pb="42px" pt="38px" px="1px" justify="center" align="center" w="full">
        <OTPInput
          w="full"
          h="55.658px"
          value={code}
          noInputs={6}
          type="number"
          fontWeight={'300'}
          borderRadius="12px"
          fontSize={'35.621px'}
          border="1px solid #E4E4E4"
          onChange={value => setCode(value)}
          style={{color: '#3D3D3D', backgroundColor: '#E5E5E5'}}
        />
      </Flex>
      <Button
        isDisabled={code.length < 6}
        width="350px"
        fontWeight="400"
        fontStyle="normal"
        fontSize="16px"
        variant={'dark'}
        borderRadius="full"
        border="1px solid #000"
        fontFamily="Euclid Circular B"
        onClick={handleVerifyDividendPayment}
      >
        {'Proceed'}
      </Button>
    </Stack>
  );
};
export default VerifyUserViaOTP;
