// const countries = [
//   {
//     name: 'Afghanistan',
//     code: 'AF',
//     currency: 'Afghan Afghani',
//     abbreviation: 'AFN',
//     locale: 'fa-AF',
//     symbol: '؋',
//   },
//   {
//     name: 'Albania',
//     code: 'AL',
//     currency: 'Albanian Lek',
//     abbreviation: 'ALL',
//     locale: 'sq-AL',
//     symbol: 'L',
//   },
//   {
//     name: 'Algeria',
//     code: 'DZ',
//     currency: 'Algerian Dinar',
//     abbreviation: 'DZD',
//     locale: 'ar-DZ',
//     symbol: 'د.ج',
//   },
//   {
//     name: 'Andorra',
//     code: 'AD',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'ca-AD',
//     symbol: '€',
//   },
//   {
//     name: 'Angola',
//     code: 'AO',
//     currency: 'Angolan Kwanza',
//     abbreviation: 'AOA',
//     locale: 'pt-AO',
//     symbol: 'Kz',
//   },
//   {
//     name: 'Argentina',
//     code: 'AR',
//     currency: 'Argentine Peso',
//     abbreviation: 'ARS',
//     locale: 'es-AR',
//     symbol: '$',
//   },
//   {
//     name: 'Armenia',
//     code: 'AM',
//     currency: 'Armenian Dram',
//     abbreviation: 'AMD',
//     locale: 'hy-AM',
//     symbol: '֏',
//   },
//   {
//     name: 'Australia',
//     code: 'AU',
//     currency: 'Australian Dollar',
//     abbreviation: 'AUD',
//     locale: 'en-AU',
//     symbol: '$',
//   },
//   {
//     name: 'Austria',
//     code: 'AT',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'de-AT',
//     symbol: '€',
//   },
//   {
//     name: 'Azerbaijan',
//     code: 'AZ',
//     currency: 'Azerbaijani Manat',
//     abbreviation: 'AZN',
//     locale: 'az-AZ',
//     symbol: '₼',
//   },
//   {
//     name: 'Bahamas',
//     code: 'BS',
//     currency: 'Bahamian Dollar',
//     abbreviation: 'BSD',
//     locale: 'en-BS',
//     symbol: '$',
//   },
//   {
//     name: 'Bahrain',
//     code: 'BH',
//     currency: 'Bahraini Dinar',
//     abbreviation: 'BHD',
//     locale: 'ar-BH',
//     symbol: '.د.ب',
//   },
//   {
//     name: 'Bangladesh',
//     code: 'BD',
//     currency: 'Bangladeshi Taka',
//     abbreviation: 'BDT',
//     locale: 'bn-BD',
//     symbol: '৳',
//   },
//   {
//     name: 'Barbados',
//     code: 'BB',
//     currency: 'Barbadian Dollar',
//     abbreviation: 'BBD',
//     locale: 'en-BB',
//     symbol: '$',
//   },
//   {
//     name: 'Belarus',
//     code: 'BY',
//     currency: 'Belarusian Ruble',
//     abbreviation: 'BYN',
//     locale: 'be-BY',
//     symbol: 'Br',
//   },
//   {
//     name: 'Belgium',
//     code: 'BE',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'nl-BE',
//     symbol: '€',
//   },
//   {
//     name: 'Belize',
//     code: 'BZ',
//     currency: 'Belize Dollar',
//     abbreviation: 'BZD',
//     locale: 'en-BZ',
//     symbol: 'BZ$',
//   },
//   {
//     name: 'Benin',
//     code: 'BJ',
//     currency: 'West African CFA Franc',
//     abbreviation: 'XOF',
//     locale: 'fr-BJ',
//     symbol: 'CFA',
//   },
//   {
//     name: 'Bhutan',
//     code: 'BT',
//     currency: 'Bhutanese Ngultrum',
//     abbreviation: 'BTN',
//     locale: 'dz-BT',
//     symbol: 'Nu.',
//   },
//   {
//     name: 'Bolivia',
//     code: 'BO',
//     currency: 'Bolivian Boliviano',
//     abbreviation: 'BOB',
//     locale: 'es-BO',
//     symbol: 'Bs.',
//   },
//   {
//     name: 'Bosnia and Herzegovina',
//     code: 'BA',
//     currency: 'Bosnia-Herzegovina Convertible Mark',
//     abbreviation: 'BAM',
//     locale: 'bs-BA',
//     symbol: 'KM',
//   },
//   {
//     name: 'Botswana',
//     code: 'BW',
//     currency: 'Botswana Pula',
//     abbreviation: 'BWP',
//     locale: 'en-BW',
//     symbol: 'P',
//   },
//   {
//     name: 'Brazil',
//     code: 'BR',
//     currency: 'Brazilian Real',
//     abbreviation: 'BRL',
//     locale: 'pt-BR',
//     symbol: 'R$',
//   },
//   {
//     name: 'Brunei',
//     code: 'BN',
//     currency: 'Brunei Dollar',
//     abbreviation: 'BND',
//     locale: 'ms-BN',
//     symbol: '$',
//   },
//   {
//     name: 'Bulgaria',
//     code: 'BG',
//     currency: 'Bulgarian Lev',
//     abbreviation: 'BGN',
//     locale: 'bg-BG',
//     symbol: 'лв',
//   },
//   {
//     name: 'Burkina Faso',
//     code: 'BF',
//     currency: 'West African CFA Franc',
//     abbreviation: 'XOF',
//     locale: 'fr-BF',
//     symbol: 'CFA',
//   },
//   {
//     name: 'Burundi',
//     code: 'BI',
//     currency: 'Burundian Franc',
//     abbreviation: 'BIF',
//     locale: 'rn-BI',
//     symbol: 'FBu',
//   },
//   {
//     name: 'Cabo Verde',
//     code: 'CV',
//     currency: 'Cape Verdean Escudo',
//     abbreviation: 'CVE',
//     locale: 'pt-CV',
//     symbol: '$',
//   },
//   {
//     name: 'Cambodia',
//     code: 'KH',
//     currency: 'Cambodian Riel',
//     abbreviation: 'KHR',
//     locale: 'km-KH',
//     symbol: '៛',
//   },
//   {
//     name: 'Cameroon',
//     code: 'CM',
//     currency: 'Central African CFA Franc',
//     abbreviation: 'XAF',
//     locale: 'fr-CM',
//     symbol: 'FCFA',
//   },
//   {
//     name: 'Canada',
//     code: 'CA',
//     currency: 'Canadian Dollar',
//     abbreviation: 'CAD',
//     locale: 'en-CA',
//     symbol: '$',
//   },
//   {
//     name: 'Central African Republic',
//     code: 'CF',
//     currency: 'Central African CFA Franc',
//     abbreviation: 'XAF',
//     locale: 'fr-CF',
//     symbol: 'FCFA',
//   },
//   {
//     name: 'Chad',
//     code: 'TD',
//     currency: 'Central African CFA Franc',
//     abbreviation: 'XAF',
//     locale: 'fr-TD',
//     symbol: 'FCFA',
//   },
//   {
//     name: 'Chile',
//     code: 'CL',
//     currency: 'Chilean Peso',
//     abbreviation: 'CLP',
//     locale: 'es-CL',
//     symbol: '$',
//   },
//   {
//     name: 'China',
//     code: 'CN',
//     currency: 'Chinese Yuan',
//     abbreviation: 'CNY',
//     locale: 'zh-CN',
//     symbol: '¥',
//   },
//   {
//     name: 'Colombia',
//     code: 'CO',
//     currency: 'Colombian Peso',
//     abbreviation: 'COP',
//     locale: 'es-CO',
//     symbol: '$',
//   },
//   {
//     name: 'Comoros',
//     code: 'KM',
//     currency: 'Comorian Franc',
//     abbreviation: 'KMF',
//     locale: 'ar-KM',
//     symbol: 'CF',
//   },
//   {
//     name: 'Congo (Congo-Brazzaville)',
//     code: 'CG',
//     currency: 'Central African CFA Franc',
//     abbreviation: 'XAF',
//     locale: 'fr-CG',
//     symbol: 'FCFA',
//   },
//   {
//     name: 'Congo (Democratic Republic)',
//     code: 'CD',
//     currency: 'Congolese Franc',
//     abbreviation: 'CDF',
//     locale: 'fr-CD',
//     symbol: 'FC',
//   },
//   {
//     name: 'Costa Rica',
//     code: 'CR',
//     currency: 'Costa Rican Colón',
//     abbreviation: 'CRC',
//     locale: 'es-CR',
//     symbol: '₡',
//   },
//   {
//     name: 'Croatia',
//     code: 'HR',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'hr-HR',
//     symbol: '€',
//   },
//   {
//     name: 'Cuba',
//     code: 'CU',
//     currency: 'Cuban Peso',
//     abbreviation: 'CUP',
//     locale: 'es-CU',
//     symbol: '$',
//   },
//   {name: 'Cyprus', code: 'CY', currency: 'Euro', abbreviation: 'EUR', locale: 'el-CY', symbol: '€'},
//   {
//     name: 'Czechia',
//     code: 'CZ',
//     currency: 'Czech Koruna',
//     abbreviation: 'CZK',
//     locale: 'cs-CZ',
//     symbol: 'Kč',
//   },
//   {
//     name: 'Denmark',
//     code: 'DK',
//     currency: 'Danish Krone',
//     abbreviation: 'DKK',
//     locale: 'da-DK',
//     symbol: 'kr',
//   },
//   {
//     name: 'Djibouti',
//     code: 'DJ',
//     currency: 'Djiboutian Franc',
//     abbreviation: 'DJF',
//     locale: 'fr-DJ',
//     symbol: 'Fdj',
//   },
//   {
//     name: 'Dominica',
//     code: 'DM',
//     currency: 'East Caribbean Dollar',
//     abbreviation: 'XCD',
//     locale: 'en-DM',
//     symbol: '$',
//   },
//   {
//     name: 'Dominican Republic',
//     code: 'DO',
//     currency: 'Dominican Peso',
//     abbreviation: 'DOP',
//     locale: 'es-DO',
//     symbol: 'RD$',
//   },
//   {
//     name: 'Ecuador',
//     code: 'EC',
//     currency: 'United States Dollar',
//     abbreviation: 'USD',
//     locale: 'es-EC',
//     symbol: '$',
//   },
//   {
//     name: 'Egypt',
//     code: 'EG',
//     currency: 'Egyptian Pound',
//     abbreviation: 'EGP',
//     locale: 'ar-EG',
//     symbol: 'ج.م',
//   },
//   {
//     name: 'El Salvador',
//     code: 'SV',
//     currency: 'United States Dollar',
//     abbreviation: 'USD',
//     locale: 'es-SV',
//     symbol: '$',
//   },
//   {
//     name: 'Estonia',
//     code: 'EE',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'et-EE',
//     symbol: '€',
//   },
//   {
//     name: 'Ethiopia',
//     code: 'ET',
//     currency: 'Ethiopian Birr',
//     abbreviation: 'ETB',
//     locale: 'am-ET',
//     symbol: 'Br',
//   },
//   {
//     name: 'Fiji',
//     code: 'FJ',
//     currency: 'Fijian Dollar',
//     abbreviation: 'FJD',
//     locale: 'en-FJ',
//     symbol: '$',
//   },
//   {
//     name: 'Finland',
//     code: 'FI',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'fi-FI',
//     symbol: '€',
//   },
//   {name: 'France', code: 'FR', currency: 'Euro', abbreviation: 'EUR', locale: 'fr-FR', symbol: '€'},
//   {
//     name: 'Gabon',
//     code: 'GA',
//     currency: 'Central African CFA Franc',
//     abbreviation: 'XAF',
//     locale: 'fr-GA',
//     symbol: 'FCFA',
//   },
//   {
//     name: 'Gambia',
//     code: 'GM',
//     currency: 'Gambian Dalasi',
//     abbreviation: 'GMD',
//     locale: 'en-GM',
//     symbol: 'D',
//   },
//   {
//     name: 'Georgia',
//     code: 'GE',
//     currency: 'Georgian Lari',
//     abbreviation: 'GEL',
//     locale: 'ka-GE',
//     symbol: '₾',
//   },
//   {
//     name: 'Germany',
//     code: 'DE',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'de-DE',
//     symbol: '€',
//   },
//   {
//     name: 'Ghana',
//     code: 'GH',
//     currency: 'Ghanaian Cedi',
//     abbreviation: 'GHS',
//     locale: 'en-GH',
//     symbol: '₵',
//   },
//   {name: 'Greece', code: 'GR', currency: 'Euro', abbreviation: 'EUR', locale: 'el-GR', symbol: '€'},
//   {
//     name: 'Grenada',
//     code: 'GD',
//     currency: 'East Caribbean Dollar',
//     abbreviation: 'XCD',
//     locale: 'en-GD',
//     symbol: '$',
//   },
//   {
//     name: 'Guatemala',
//     code: 'GT',
//     currency: 'Guatemalan Quetzal',
//     abbreviation: 'GTQ',
//     locale: 'es-GT',
//     symbol: 'Q',
//   },
//   {
//     name: 'Guinea',
//     code: 'GN',
//     currency: 'Guinean Franc',
//     abbreviation: 'GNF',
//     locale: 'fr-GN',
//     symbol: 'FG',
//   },
//   {
//     name: 'Guinea-Bissau',
//     code: 'GW',
//     currency: 'West African CFA Franc',
//     abbreviation: 'XOF',
//     locale: 'pt-GW',
//     symbol: 'CFA',
//   },
//   {
//     name: 'Guyana',
//     code: 'GY',
//     currency: 'Guyanese Dollar',
//     abbreviation: 'GYD',
//     locale: 'en-GY',
//     symbol: '$',
//   },
//   {
//     name: 'Haiti',
//     code: 'HT',
//     currency: 'Haitian Gourde',
//     abbreviation: 'HTG',
//     locale: 'ht-HT',
//     symbol: 'G',
//   },
//   {
//     name: 'Honduras',
//     code: 'HN',
//     currency: 'Honduran Lempira',
//     abbreviation: 'HNL',
//     locale: 'es-HN',
//     symbol: 'L',
//   },
//   {
//     name: 'Hungary',
//     code: 'HU',
//     currency: 'Hungarian Forint',
//     abbreviation: 'HUF',
//     locale: 'hu-HU',
//     symbol: 'Ft',
//   },
//   {
//     name: 'Iceland',
//     code: 'IS',
//     currency: 'Icelandic Króna',
//     abbreviation: 'ISK',
//     locale: 'is-IS',
//     symbol: 'kr',
//   },
//   {
//     name: 'India',
//     code: 'IN',
//     currency: 'Indian Rupee',
//     abbreviation: 'INR',
//     locale: 'hi-IN',
//     symbol: '₹',
//   },
//   {
//     name: 'Indonesia',
//     code: 'ID',
//     currency: 'Indonesian Rupiah',
//     abbreviation: 'IDR',
//     locale: 'id-ID',
//     symbol: 'Rp',
//   },
//   {
//     name: 'Iran',
//     code: 'IR',
//     currency: 'Iranian Rial',
//     abbreviation: 'IRR',
//     locale: 'fa-IR',
//     symbol: '﷼',
//   },
//   {
//     name: 'Iraq',
//     code: 'IQ',
//     currency: 'Iraqi Dinar',
//     abbreviation: 'IQD',
//     locale: 'ar-IQ',
//     symbol: 'ع.د',
//   },
//   {
//     name: 'Ireland',
//     code: 'IE',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'en-IE',
//     symbol: '€',
//   },
//   {
//     name: 'Israel',
//     code: 'IL',
//     currency: 'Israeli New Shekel',
//     abbreviation: 'ILS',
//     locale: 'he-IL',
//     symbol: '₪',
//   },
//   {name: 'Italy', code: 'IT', currency: 'Euro', abbreviation: 'EUR', locale: 'it-IT', symbol: '€'},
//   {
//     name: 'Jamaica',
//     code: 'JM',
//     currency: 'Jamaican Dollar',
//     abbreviation: 'JMD',
//     locale: 'en-JM',
//     symbol: 'J$',
//   },
//   {
//     name: 'Japan',
//     code: 'JP',
//     currency: 'Japanese Yen',
//     abbreviation: 'JPY',
//     locale: 'ja-JP',
//     symbol: '¥',
//   },
//   {
//     name: 'Jordan',
//     code: 'JO',
//     currency: 'Jordanian Dinar',
//     abbreviation: 'JOD',
//     locale: 'ar-JO',
//     symbol: 'د.ا',
//   },
//   {
//     name: 'Kazakhstan',
//     code: 'KZ',
//     currency: 'Kazakhstani Tenge',
//     abbreviation: 'KZT',
//     locale: 'kk-KZ',
//     symbol: '₸',
//   },
//   {
//     name: 'Kenya',
//     code: 'KE',
//     currency: 'Kenyan Shilling',
//     abbreviation: 'KES',
//     locale: 'sw-KE',
//     symbol: 'KSh',
//   },
//   {
//     name: 'Kiribati',
//     code: 'KI',
//     currency: 'Australian Dollar',
//     abbreviation: 'AUD',
//     locale: 'en-KI',
//     symbol: '$',
//   },
//   {
//     name: 'Kuwait',
//     code: 'KW',
//     currency: 'Kuwaiti Dinar',
//     abbreviation: 'KWD',
//     locale: 'ar-KW',
//     symbol: 'د.ك',
//   },
//   {
//     name: 'Kyrgyzstan',
//     code: 'KG',
//     currency: 'Kyrgyzstani Som',
//     abbreviation: 'KGS',
//     locale: 'ky-KG',
//     symbol: 'с',
//   },
//   {
//     name: 'Laos',
//     code: 'LA',
//     currency: 'Lao Kip',
//     abbreviation: 'LAK',
//     locale: 'lo-LA',
//     symbol: '₭',
//   },
//   {name: 'Latvia', code: 'LV', currency: 'Euro', abbreviation: 'EUR', locale: 'lv-LV', symbol: '€'},
//   {
//     name: 'Lebanon',
//     code: 'LB',
//     currency: 'Lebanese Pound',
//     abbreviation: 'LBP',
//     locale: 'ar-LB',
//     symbol: 'ل.ل',
//   },
//   {
//     name: 'Lesotho',
//     code: 'LS',
//     currency: 'Lesotho Loti',
//     abbreviation: 'LSL',
//     locale: 'st-LS',
//     symbol: 'L',
//   },
//   {
//     name: 'Liberia',
//     code: 'LR',
//     currency: 'Liberian Dollar',
//     abbreviation: 'LRD',
//     locale: 'en-LR',
//     symbol: '$',
//   },
//   {
//     name: 'Libya',
//     code: 'LY',
//     currency: 'Libyan Dinar',
//     abbreviation: 'LYD',
//     locale: 'ar-LY',
//     symbol: 'ل.د',
//   },
//   {
//     name: 'Liechtenstein',
//     code: 'LI',
//     currency: 'Swiss Franc',
//     abbreviation: 'CHF',
//     locale: 'de-LI',
//     symbol: 'CHF',
//   },
//   {
//     name: 'Lithuania',
//     code: 'LT',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'lt-LT',
//     symbol: '€',
//   },
//   {
//     name: 'Luxembourg',
//     code: 'LU',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'fr-LU',
//     symbol: '€',
//   },
//   {
//     name: 'Madagascar',
//     code: 'MG',
//     currency: 'Malagasy Ariary',
//     abbreviation: 'MGA',
//     locale: 'mg-MG',
//     symbol: 'Ar',
//   },
//   {
//     name: 'Malawi',
//     code: 'MW',
//     currency: 'Malawian Kwacha',
//     abbreviation: 'MWK',
//     locale: 'ny-MW',
//     symbol: 'MK',
//   },
//   {
//     name: 'Malaysia',
//     code: 'MY',
//     currency: 'Malaysian Ringgit',
//     abbreviation: 'MYR',
//     locale: 'ms-MY',
//     symbol: 'RM',
//   },
//   {
//     name: 'Maldives',
//     code: 'MV',
//     currency: 'Maldivian Rufiyaa',
//     abbreviation: 'MVR',
//     locale: 'dv-MV',
//     symbol: '.ރ',
//   },
//   {
//     name: 'Mali',
//     code: 'ML',
//     currency: 'West African CFA Franc',
//     abbreviation: 'XOF',
//     locale: 'fr-ML',
//     symbol: 'CFA',
//   },
//   {name: 'Malta', code: 'MT', currency: 'Euro', abbreviation: 'EUR', locale: 'mt-MT', symbol: '€'},
//   {
//     name: 'Marshall Islands',
//     code: 'MH',
//     currency: 'United States Dollar',
//     abbreviation: 'USD',
//     locale: 'mh-MH',
//     symbol: '$',
//   },
//   {
//     name: 'Mauritania',
//     code: 'MR',
//     currency: 'Mauritanian Ouguiya',
//     abbreviation: 'MRU',
//     locale: 'ar-MR',
//     symbol: 'UM',
//   },
//   {
//     name: 'Mauritius',
//     code: 'MU',
//     currency: 'Mauritian Rupee',
//     abbreviation: 'MUR',
//     locale: 'en-MU',
//     symbol: '₨',
//   },
//   {
//     name: 'Mexico',
//     code: 'MX',
//     currency: 'Mexican Peso',
//     abbreviation: 'MXN',
//     locale: 'es-MX',
//     symbol: '$',
//   },
//   {
//     name: 'Micronesia',
//     code: 'FM',
//     currency: 'United States Dollar',
//     abbreviation: 'USD',
//     locale: 'en-FM',
//     symbol: '$',
//   },
//   {
//     name: 'Moldova',
//     code: 'MD',
//     currency: 'Moldovan Leu',
//     abbreviation: 'MDL',
//     locale: 'ro-MD',
//     symbol: 'L',
//   },
//   {name: 'Monaco', code: 'MC', currency: 'Euro', abbreviation: 'EUR', locale: 'fr-MC', symbol: '€'},
//   {
//     name: 'Mongolia',
//     code: 'MN',
//     currency: 'Mongolian Tögrög',
//     abbreviation: 'MNT',
//     locale: 'mn-MN',
//     symbol: '₮',
//   },
//   {
//     name: 'Montenegro',
//     code: 'ME',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'sr-ME',
//     symbol: '€',
//   },
//   {
//     name: 'Morocco',
//     code: 'MA',
//     currency: 'Moroccan Dirham',
//     abbreviation: 'MAD',
//     locale: 'ar-MA',
//     symbol: 'د.م.',
//   },
//   {
//     name: 'Mozambique',
//     code: 'MZ',
//     currency: 'Mozambican Metical',
//     abbreviation: 'MZN',
//     locale: 'pt-MZ',
//     symbol: 'MT',
//   },
//   {
//     name: 'Myanmar (Burma)',
//     code: 'MM',
//     currency: 'Myanmar Kyat',
//     abbreviation: 'MMK',
//     locale: 'my-MM',
//     symbol: 'K',
//   },
//   {
//     name: 'Namibia',
//     code: 'NA',
//     currency: 'Namibian Dollar',
//     abbreviation: 'NAD',
//     locale: 'en-NA',
//     symbol: '$',
//   },
//   {
//     name: 'Nauru',
//     code: 'NR',
//     currency: 'Australian Dollar',
//     abbreviation: 'AUD',
//     locale: 'na-NR',
//     symbol: '$',
//   },
//   {
//     name: 'Nepal',
//     code: 'NP',
//     currency: 'Nepalese Rupee',
//     abbreviation: 'NPR',
//     locale: 'ne-NP',
//     symbol: '₨',
//   },
//   {
//     name: 'Netherlands',
//     code: 'NL',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'nl-NL',
//     symbol: '€',
//   },
//   {
//     name: 'New Zealand',
//     code: 'NZ',
//     currency: 'New Zealand Dollar',
//     abbreviation: 'NZD',
//     locale: 'en-NZ',
//     symbol: '$',
//   },
//   {
//     name: 'Nicaragua',
//     code: 'NI',
//     currency: 'Nicaraguan Córdoba',
//     abbreviation: 'NIO',
//     locale: 'es-NI',
//     symbol: 'C$',
//   },
//   {
//     name: 'Niger',
//     code: 'NE',
//     currency: 'West African CFA Franc',
//     abbreviation: 'XOF',
//     locale: 'fr-NE',
//     symbol: 'CFA',
//   },
//   {
//     name: 'Nigeria',
//     code: 'NG',
//     currency: 'Nigerian Naira',
//     abbreviation: 'NGN',
//     locale: 'en-NG',
//     symbol: '₦',
//   },
//   {
//     name: 'North Korea',
//     code: 'KP',
//     currency: 'North Korean Won',
//     abbreviation: 'KPW',
//     locale: 'ko-KP',
//     symbol: '₩',
//   },
//   {
//     name: 'North Macedonia',
//     code: 'MK',
//     currency: 'Macedonian Denar',
//     abbreviation: 'MKD',
//     locale: 'mk-MK',
//     symbol: 'ден',
//   },
//   {
//     name: 'Norway',
//     code: 'NO',
//     currency: 'Norwegian Krone',
//     abbreviation: 'NOK',
//     locale: 'nb-NO',
//     symbol: 'kr',
//   },
//   {
//     name: 'Oman',
//     code: 'OM',
//     currency: 'Omani Rial',
//     abbreviation: 'OMR',
//     locale: 'ar-OM',
//     symbol: 'ر.ع.',
//   },
//   {
//     name: 'Pakistan',
//     code: 'PK',
//     currency: 'Pakistani Rupee',
//     abbreviation: 'PKR',
//     locale: 'ur-PK',
//     symbol: '₨',
//   },
//   {
//     name: 'Palau',
//     code: 'PW',
//     currency: 'United States Dollar',
//     abbreviation: 'USD',
//     locale: 'pau-PW',
//     symbol: '$',
//   },
//   {
//     name: 'Panama',
//     code: 'PA',
//     currency: 'Panamanian Balboa',
//     abbreviation: 'PAB',
//     locale: 'es-PA',
//     symbol: 'B/.',
//   },
//   {
//     name: 'Papua New Guinea',
//     code: 'PG',
//     currency: 'Papua New Guinean Kina',
//     abbreviation: 'PGK',
//     locale: 'en-PG',
//     symbol: 'K',
//   },
//   {
//     name: 'Paraguay',
//     code: 'PY',
//     currency: 'Paraguayan Guaraní',
//     abbreviation: 'PYG',
//     locale: 'es-PY',
//     symbol: '₲',
//   },
//   {
//     name: 'Peru',
//     code: 'PE',
//     currency: 'Peruvian Sol',
//     abbreviation: 'PEN',
//     locale: 'es-PE',
//     symbol: 'S/.',
//   },
//   {
//     name: 'Philippines',
//     code: 'PH',
//     currency: 'Philippine Peso',
//     abbreviation: 'PHP',
//     locale: 'fil-PH',
//     symbol: '₱',
//   },
//   {
//     name: 'Poland',
//     code: 'PL',
//     currency: 'Polish Złoty',
//     abbreviation: 'PLN',
//     locale: 'pl-PL',
//     symbol: 'zł',
//   },
//   {
//     name: 'Portugal',
//     code: 'PT',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'pt-PT',
//     symbol: '€',
//   },
//   {
//     name: 'Qatar',
//     code: 'QA',
//     currency: 'Qatari Riyal',
//     abbreviation: 'QAR',
//     locale: 'ar-QA',
//     symbol: 'ر.ق',
//   },
//   {
//     name: 'Romania',
//     code: 'RO',
//     currency: 'Romanian Leu',
//     abbreviation: 'RON',
//     locale: 'ro-RO',
//     symbol: 'lei',
//   },
//   {
//     name: 'Russia',
//     code: 'RU',
//     currency: 'Russian Ruble',
//     abbreviation: 'RUB',
//     locale: 'ru-RU',
//     symbol: '₽',
//   },
//   {
//     name: 'Rwanda',
//     code: 'RW',
//     currency: 'Rwandan Franc',
//     abbreviation: 'RWF',
//     locale: 'rw-RW',
//     symbol: 'FRw',
//   },
//   {
//     name: 'Saint Kitts and Nevis',
//     code: 'KN',
//     currency: 'East Caribbean Dollar',
//     abbreviation: 'XCD',
//     locale: 'en-KN',
//     symbol: '$',
//   },
//   {
//     name: 'Saint Lucia',
//     code: 'LC',
//     currency: 'East Caribbean Dollar',
//     abbreviation: 'XCD',
//     locale: 'en-LC',
//     symbol: '$',
//   },
//   {
//     name: 'Saint Vincent and the Grenadines',
//     code: 'VC',
//     currency: 'East Caribbean Dollar',
//     abbreviation: 'XCD',
//     locale: 'en-VC',
//     symbol: '$',
//   },
//   {
//     name: 'Samoa',
//     code: 'WS',
//     currency: 'Samoan Tala',
//     abbreviation: 'WST',
//     locale: 'sm-WS',
//     symbol: 'T',
//   },
//   {
//     name: 'San Marino',
//     code: 'SM',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'it-SM',
//     symbol: '€',
//   },
//   {
//     name: 'São Tomé and Príncipe',
//     code: 'ST',
//     currency: 'São Tomé and Príncipe Dobra',
//     abbreviation: 'STN',
//     locale: 'pt-ST',
//     symbol: 'Db',
//   },
//   {
//     name: 'Saudi Arabia',
//     code: 'SA',
//     currency: 'Saudi Riyal',
//     abbreviation: 'SAR',
//     locale: 'ar-SA',
//     symbol: 'ر.س',
//   },
//   {
//     name: 'Senegal',
//     code: 'SN',
//     currency: 'West African CFA Franc',
//     abbreviation: 'XOF',
//     locale: 'fr-SN',
//     symbol: 'CFA',
//   },
//   {
//     name: 'Serbia',
//     code: 'RS',
//     currency: 'Serbian Dinar',
//     abbreviation: 'RSD',
//     locale: 'sr-RS',
//     symbol: 'дин.',
//   },
//   {
//     name: 'Seychelles',
//     code: 'SC',
//     currency: 'Seychellois Rupee',
//     abbreviation: 'SCR',
//     locale: 'en-SC',
//     symbol: '₨',
//   },
//   {
//     name: 'Sierra Leone',
//     code: 'SL',
//     currency: 'Sierra Leonean Leone',
//     abbreviation: 'SLE',
//     locale: 'en-SL',
//     symbol: 'Le',
//   },
//   {
//     name: 'Singapore',
//     code: 'SG',
//     currency: 'Singapore Dollar',
//     abbreviation: 'SGD',
//     locale: 'en-SG',
//     symbol: '$',
//   },
//   {
//     name: 'Slovakia',
//     code: 'SK',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'sk-SK',
//     symbol: '€',
//   },
//   {
//     name: 'Slovenia',
//     code: 'SI',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'sl-SI',
//     symbol: '€',
//   },
//   {
//     name: 'Solomon Islands',
//     code: 'SB',
//     currency: 'Solomon Islands Dollar',
//     abbreviation: 'SBD',
//     locale: 'en-SB',
//     symbol: '$',
//   },
//   {
//     name: 'Somalia',
//     code: 'SO',
//     currency: 'Somali Shilling',
//     abbreviation: 'SOS',
//     locale: 'so-SO',
//     symbol: 'Sh',
//   },
//   {
//     name: 'South Africa',
//     code: 'ZA',
//     currency: 'South African Rand',
//     abbreviation: 'ZAR',
//     locale: 'en-ZA',
//     symbol: 'R',
//   },
//   {
//     name: 'South Korea',
//     code: 'KR',
//     currency: 'South Korean Won',
//     abbreviation: 'KRW',
//     locale: 'ko-KR',
//     symbol: '₩',
//   },
//   {
//     name: 'South Sudan',
//     code: 'SS',
//     currency: 'South Sudanese Pound',
//     abbreviation: 'SSP',
//     locale: 'en-SS',
//     symbol: '£',
//   },
//   {name: 'Spain', code: 'ES', currency: 'Euro', abbreviation: 'EUR', locale: 'es-ES', symbol: '€'},
//   {
//     name: 'Sri Lanka',
//     code: 'LK',
//     currency: 'Sri Lankan Rupee',
//     abbreviation: 'LKR',
//     locale: 'si-LK',
//     symbol: '₨',
//   },
//   {
//     name: 'Sudan',
//     code: 'SD',
//     currency: 'Sudanese Pound',
//     abbreviation: 'SDG',
//     locale: 'ar-SD',
//     symbol: 'ج.س.',
//   },
//   {
//     name: 'Suriname',
//     code: 'SR',
//     currency: 'Surinamese Dollar',
//     abbreviation: 'SRD',
//     locale: 'nl-SR',
//     symbol: '$',
//   },
//   {
//     name: 'Sweden',
//     code: 'SE',
//     currency: 'Swedish Krona',
//     abbreviation: 'SEK',
//     locale: 'sv-SE',
//     symbol: 'kr',
//   },
//   {
//     name: 'Switzerland',
//     code: 'CH',
//     currency: 'Swiss Franc',
//     abbreviation: 'CHF',
//     locale: 'de-CH',
//     symbol: 'CHF',
//   },
//   {
//     name: 'Syria',
//     code: 'SY',
//     currency: 'Syrian Pound',
//     abbreviation: 'SYP',
//     locale: 'ar-SY',
//     symbol: '£',
//   },
//   {
//     name: 'Taiwan',
//     code: 'TW',
//     currency: 'New Taiwan Dollar',
//     abbreviation: 'TWD',
//     locale: 'zh-TW',
//     symbol: 'NT$',
//   },
//   {
//     name: 'Tajikistan',
//     code: 'TJ',
//     currency: 'Tajikistani Somoni',
//     abbreviation: 'TJS',
//     locale: 'tg-TJ',
//     symbol: 'ЅМ',
//   },
//   {
//     name: 'Tanzania',
//     code: 'TZ',
//     currency: 'Tanzanian Shilling',
//     abbreviation: 'TZS',
//     locale: 'sw-TZ',
//     symbol: 'TSh',
//   },
//   {
//     name: 'Thailand',
//     code: 'TH',
//     currency: 'Thai Baht',
//     abbreviation: 'THB',
//     locale: 'th-TH',
//     symbol: '฿',
//   },
//   {
//     name: 'Togo',
//     code: 'TG',
//     currency: 'West African CFA Franc',
//     abbreviation: 'XOF',
//     locale: 'fr-TG',
//     symbol: 'CFA',
//   },
//   {
//     name: 'Tonga',
//     code: 'TO',
//     currency: 'Tongan Paʻanga',
//     abbreviation: 'TOP',
//     locale: 'to-TO',
//     symbol: 'T$',
//   },
//   {
//     name: 'Trinidad and Tobago',
//     code: 'TT',
//     currency: 'Trinidad and Tobago Dollar',
//     abbreviation: 'TTD',
//     locale: 'en-TT',
//     symbol: 'TT$',
//   },
//   {
//     name: 'Tunisia',
//     code: 'TN',
//     currency: 'Tunisian Dinar',
//     abbreviation: 'TND',
//     locale: 'ar-TN',
//     symbol: 'د.ت',
//   },
//   {
//     name: 'Turkey',
//     code: 'TR',
//     currency: 'Turkish Lira',
//     abbreviation: 'TRY',
//     locale: 'tr-TR',
//     symbol: '₺',
//   },
//   {
//     name: 'Turkmenistan',
//     code: 'TM',
//     currency: 'Turkmenistan Manat',
//     abbreviation: 'TMT',
//     locale: 'tk-TM',
//     symbol: 'm',
//   },
//   {
//     name: 'Tuvalu',
//     code: 'TV',
//     currency: 'Australian Dollar',
//     abbreviation: 'AUD',
//     locale: 'tvl-TV',
//     symbol: '$',
//   },
//   {
//     name: 'Uganda',
//     code: 'UG',
//     currency: 'Ugandan Shilling',
//     abbreviation: 'UGX',
//     locale: 'sw-UG',
//     symbol: 'USh',
//   },
//   {
//     name: 'Ukraine',
//     code: 'UA',
//     currency: 'Ukrainian Hryvnia',
//     abbreviation: 'UAH',
//     locale: 'uk-UA',
//     symbol: '₴',
//   },
//   {
//     name: 'United Arab Emirates',
//     code: 'AE',
//     currency: 'United Arab Emirates Dirham',
//     abbreviation: 'AED',
//     locale: 'ar-AE',
//     symbol: 'د.إ',
//   },
//   {
//     name: 'United Kingdom',
//     code: 'GB',
//     currency: 'Pound Sterling',
//     abbreviation: 'GBP',
//     locale: 'en-GB',
//     symbol: '£',
//   },
//   {
//     name: 'United States Of America',
//     code: 'US',
//     currency: 'United States Dollar',
//     abbreviation: 'USD',
//     locale: 'en-US',
//     symbol: '$',
//   },
//   {
//     name: 'Uruguay',
//     code: 'UY',
//     currency: 'Uruguayan Peso',
//     abbreviation: 'UYU',
//     locale: 'es-UY',
//     symbol: '$U',
//   },
//   {
//     name: 'Uzbekistan',
//     code: 'UZ',
//     currency: 'Uzbekistani Som',
//     abbreviation: 'UZS',
//     locale: 'uz-UZ',
//     symbol: 'лв',
//   },
//   {
//     name: 'Vanuatu',
//     code: 'VU',
//     currency: 'Vanuatu Vatu',
//     abbreviation: 'VUV',
//     locale: 'bi-VU',
//     symbol: 'VT',
//   },
//   {
//     name: 'Vatican City',
//     code: 'VA',
//     currency: 'Euro',
//     abbreviation: 'EUR',
//     locale: 'it-VA',
//     symbol: '€',
//   },
//   {
//     name: 'Venezuela',
//     code: 'VE',
//     currency: 'Venezuelan Bolívar',
//     abbreviation: 'VES',
//     locale: 'es-VE',
//     symbol: 'Bs.',
//   },
//   {
//     name: 'Vietnam',
//     code: 'VN',
//     currency: 'Vietnamese Đồng',
//     abbreviation: 'VND',
//     locale: 'vi-VN',
//     symbol: '₫',
//   },
//   {
//     name: 'Yemen',
//     code: 'YE',
//     currency: 'Yemeni Rial',
//     abbreviation: 'YER',
//     locale: 'ar-YE',
//     symbol: '﷼',
//   },
//   {
//     name: 'Zambia',
//     code: 'ZM',
//     currency: 'Zambian Kwacha',
//     abbreviation: 'ZMW',
//     locale: 'en-ZM',
//     symbol: 'ZK',
//   },
//   {
//     name: 'Zimbabwe',
//     code: 'ZW',
//     currency: 'Zimbabwean Dollar',
//     abbreviation: 'ZWL',
//     locale: 'en-ZW',
//     symbol: 'Z$',
//   },
// ];

const countries = [
  {
    name: 'Afghanistan',
    code: 'AF',
    currency: 'Afghan Afghani',
    abbreviation: 'AFN',
    locale: 'fa-AF',
    symbol: '؋',
    timezones: ['Asia/Kabul'],
  },
  {
    name: 'Albania',
    code: 'AL',
    currency: 'Albanian Lek',
    abbreviation: 'ALL',
    locale: 'sq-AL',
    symbol: 'L',
    timezones: ['Europe/Tirane'],
  },
  {
    name: 'Algeria',
    code: 'DZ',
    currency: 'Algerian Dinar',
    abbreviation: 'DZD',
    locale: 'ar-DZ',
    symbol: 'د.ج',
    timezones: ['Africa/Algiers'],
  },
  {
    name: 'Andorra',
    code: 'AD',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'ca-AD',
    symbol: '€',
    timezones: ['Europe/Andorra'],
  },
  {
    name: 'Angola',
    code: 'AO',
    currency: 'Angolan Kwanza',
    abbreviation: 'AOA',
    locale: 'pt-AO',
    symbol: 'Kz',
    timezones: ['Africa/Luanda'],
  },
  {
    name: 'Argentina',
    code: 'AR',
    currency: 'Argentine Peso',
    abbreviation: 'ARS',
    locale: 'es-AR',
    symbol: '$',
    timezones: [
      'America/Argentina/Buenos_Aires',
      'America/Argentina/Cordoba',
      'America/Argentina/Salta',
      'America/Argentina/Jujuy',
      'America/Argentina/Tucuman',
      'America/Argentina/Catamarca',
      'America/Argentina/La_Rioja',
      'America/Argentina/San_Juan',
      'America/Argentina/Mendoza',
      'America/Argentina/San_Luis',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Ushuaia',
    ],
  },
  {
    name: 'Armenia',
    code: 'AM',
    currency: 'Armenian Dram',
    abbreviation: 'AMD',
    locale: 'hy-AM',
    symbol: '֏',
    timezones: ['Asia/Yerevan'],
  },
  {
    name: 'Australia',
    code: 'AU',
    currency: 'Australian Dollar',
    abbreviation: 'AUD',
    locale: 'en-AU',
    symbol: '$',
    timezones: [
      'Australia/Lord_Howe',
      'Australia/Sydney',
      'Australia/Melbourne',
      'Australia/Brisbane',
      'Australia/Adelaide',
      'Australia/Perth',
      'Australia/Darwin',
    ],
  },
  {
    name: 'Austria',
    code: 'AT',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'de-AT',
    symbol: '€',
    timezones: ['Europe/Vienna'],
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    currency: 'Azerbaijani Manat',
    abbreviation: 'AZN',
    locale: 'az-AZ',
    symbol: '₼',
    timezones: ['Asia/Baku'],
  },
  {
    name: 'Bahamas',
    code: 'BS',
    currency: 'Bahamian Dollar',
    abbreviation: 'BSD',
    locale: 'en-BS',
    symbol: '$',
    timezones: ['America/Nassau'],
  },
  {
    name: 'Bahrain',
    code: 'BH',
    currency: 'Bahraini Dinar',
    abbreviation: 'BHD',
    locale: 'ar-BH',
    symbol: '.د.ب',
    timezones: ['Asia/Bahrain'],
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    currency: 'Bangladeshi Taka',
    abbreviation: 'BDT',
    locale: 'bn-BD',
    symbol: '৳',
    timezones: ['Asia/Dhaka'],
  },
  {
    name: 'Barbados',
    code: 'BB',
    currency: 'Barbadian Dollar',
    abbreviation: 'BBD',
    locale: 'en-BB',
    symbol: '$',
    timezones: ['America/Barbados'],
  },
  {
    name: 'Belarus',
    code: 'BY',
    currency: 'Belarusian Ruble',
    abbreviation: 'BYN',
    locale: 'be-BY',
    symbol: 'Br',
    timezones: ['Europe/Minsk'],
  },
  {
    name: 'Belgium',
    code: 'BE',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'nl-BE',
    symbol: '€',
    timezones: ['Europe/Brussels'],
  },
  {
    name: 'Belize',
    code: 'BZ',
    currency: 'Belize Dollar',
    abbreviation: 'BZD',
    locale: 'en-BZ',
    symbol: 'BZ$',
    timezones: ['America/Belize'],
  },
  {
    name: 'Benin',
    code: 'BJ',
    currency: 'West African CFA Franc',
    abbreviation: 'XOF',
    locale: 'fr-BJ',
    symbol: 'CFA',
    timezones: ['Africa/Porto-Novo'],
  },
  {
    name: 'Bhutan',
    code: 'BT',
    currency: 'Bhutanese Ngultrum',
    abbreviation: 'BTN',
    locale: 'dz-BT',
    symbol: 'Nu.',
    timezones: ['Asia/Thimphu'],
  },
  {
    name: 'Bolivia',
    code: 'BO',
    currency: 'Bolivian Boliviano',
    abbreviation: 'BOB',
    locale: 'es-BO',
    symbol: 'Bs.',
    timezones: ['America/La_Paz'],
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    currency: 'Bosnia-Herzegovina Convertible Mark',
    abbreviation: 'BAM',
    locale: 'bs-BA',
    symbol: 'KM',
    timezones: ['Europe/Sarajevo'],
  },
  {
    name: 'Botswana',
    code: 'BW',
    currency: 'Botswana Pula',
    abbreviation: 'BWP',
    locale: 'en-BW',
    symbol: 'P',
    timezones: ['Africa/Gaborone'],
  },
  {
    name: 'Brazil',
    code: 'BR',
    currency: 'Brazilian Real',
    abbreviation: 'BRL',
    locale: 'pt-BR',
    symbol: 'R$',
    timezones: [
      'America/Sao_Paulo',
      'America/Rio_Branco',
      'America/Manaus',
      'America/Belem',
      'America/Boa_Vista',
      'America/Campo_Grande',
      'America/Cuiaba',
      'America/Fortaleza',
      'America/Maceio',
      'America/Porto_Velho',
      'America/Recife',
      'America/Santarem',
      'America/Araguaina',
      'America/Noronha',
    ],
  },
  {
    name: 'Brunei',
    code: 'BN',
    currency: 'Brunei Dollar',
    abbreviation: 'BND',
    locale: 'ms-BN',
    symbol: '$',
    timezones: ['Asia/Brunei'],
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    currency: 'Bulgarian Lev',
    abbreviation: 'BGN',
    locale: 'bg-BG',
    symbol: 'лв',
    timezones: ['Europe/Sofia'],
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    currency: 'West African CFA Franc',
    abbreviation: 'XOF',
    locale: 'fr-BF',
    symbol: 'CFA',
    timezones: ['Africa/Ouagadougou'],
  },
  {
    name: 'Burundi',
    code: 'BI',
    currency: 'Burundian Franc',
    abbreviation: 'BIF',
    locale: 'rn-BI',
    symbol: 'FBu',
    timezones: ['Africa/Bujumbura'],
  },
  {
    name: 'Cabo Verde',
    code: 'CV',
    currency: 'Cape Verdean Escudo',
    abbreviation: 'CVE',
    locale: 'pt-CV',
    symbol: '$',
    timezones: ['Atlantic/Cape_Verde'],
  },
  {
    name: 'Cambodia',
    code: 'KH',
    currency: 'Cambodian Riel',
    abbreviation: 'KHR',
    locale: 'km-KH',
    symbol: '៛',
    timezones: ['Asia/Phnom_Penh'],
  },
  {
    name: 'Cameroon',
    code: 'CM',
    currency: 'Central African CFA Franc',
    abbreviation: 'XAF',
    locale: 'fr-CM',
    symbol: 'FCFA',
    timezones: ['Africa/Douala'],
  },
  {
    name: 'Canada',
    code: 'CA',
    currency: 'Canadian Dollar',
    abbreviation: 'CAD',
    locale: 'en-CA',
    symbol: '$',
    timezones: [
      'America/St_Johns',
      'America/Halifax',
      'America/Glace_Bay',
      'America/Moncton',
      'America/Goose_Bay',
      'America/Toronto',
      'America/Montreal',
      'America/Nipigon',
      'America/Thunder_Bay',
      'America/Iqaluit',
      'America/Pangnirtung',
      'America/Winnipeg',
      'America/Regina',
      'America/Rankin_Inlet',
      'America/Edmonton',
      'America/Vancouver',
      'America/Whitehorse',
      'America/Yellowknife',
      'America/Dawson_Creek',
    ],
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    currency: 'Central African CFA Franc',
    abbreviation: 'XAF',
    locale: 'fr-CF',
    symbol: 'FCFA',
    timezones: ['Africa/Bangui'],
  },
  {
    name: 'Chad',
    code: 'TD',
    currency: 'Central African CFA Franc',
    abbreviation: 'XAF',
    locale: 'fr-TD',
    symbol: 'FCFA',
    timezones: ['Africa/Ndjamena'],
  },
  {
    name: 'Chile',
    code: 'CL',
    currency: 'Chilean Peso',
    abbreviation: 'CLP',
    locale: 'es-CL',
    symbol: '$',
    timezones: ['America/Santiago', 'America/Punta_Arenas'],
  },
  {
    name: 'China',
    code: 'CN',
    currency: 'Chinese Yuan',
    abbreviation: 'CNY',
    locale: 'zh-CN',
    symbol: '¥',
    timezones: [
      'Asia/Shanghai',
      'Asia/Urumqi',
      'Asia/Hong_Kong', // Add these if needed, as they are technically separate
      'Asia/Macau',
    ],
  },
  {
    name: 'Colombia',
    code: 'CO',
    currency: 'Colombian Peso',
    abbreviation: 'COP',
    locale: 'es-CO',
    symbol: '$',
    timezones: ['America/Bogota'],
  },
  {
    name: 'Comoros',
    code: 'KM',
    currency: 'Comorian Franc',
    abbreviation: 'KMF',
    locale: 'ar-KM',
    symbol: 'CF',
    timezones: ['Africa/Moroni'],
  },
  {
    name: 'Congo (Congo-Brazzaville)',
    code: 'CG',
    currency: 'Central African CFA Franc',
    abbreviation: 'XAF',
    locale: 'fr-CG',
    symbol: 'FCFA',
    timezones: ['Africa/Brazzaville'],
  },
  {
    name: 'Congo (Democratic Republic)',
    code: 'CD',
    currency: 'Congolese Franc',
    abbreviation: 'CDF',
    locale: 'fr-CD',
    symbol: 'FC',
    timezones: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    currency: 'Costa Rican Colón',
    abbreviation: 'CRC',
    locale: 'es-CR',
    symbol: '₡',
    timezones: ['America/Costa_Rica'],
  },
  {
    name: 'Croatia',
    code: 'HR',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'hr-HR',
    symbol: '€',
    timezones: ['Europe/Zagreb'],
  },
  {
    name: 'Cuba',
    code: 'CU',
    currency: 'Cuban Peso',
    abbreviation: 'CUP',
    locale: 'es-CU',
    symbol: '$',
    timezones: ['America/Havana'],
  },
  {
    name: 'Cyprus',
    code: 'CY',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'el-CY',
    symbol: '€',
    timezones: ['Asia/Nicosia'],
  },
  {
    name: 'Czechia',
    code: 'CZ',
    currency: 'Czech Koruna',
    abbreviation: 'CZK',
    locale: 'cs-CZ',
    symbol: 'Kč',
    timezones: ['Europe/Prague'],
  },
  {
    name: 'Denmark',
    code: 'DK',
    currency: 'Danish Krone',
    abbreviation: 'DKK',
    locale: 'da-DK',
    symbol: 'kr',
    timezones: ['Europe/Copenhagen'],
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    currency: 'Djiboutian Franc',
    abbreviation: 'DJF',
    locale: 'fr-DJ',
    symbol: 'Fdj',
    timezones: ['Africa/Djibouti'],
  },
  {
    name: 'Dominica',
    code: 'DM',
    currency: 'East Caribbean Dollar',
    abbreviation: 'XCD',
    locale: 'en-DM',
    symbol: '$',
    timezones: ['America/Dominica'],
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    currency: 'Dominican Peso',
    abbreviation: 'DOP',
    locale: 'es-DO',
    symbol: 'RD$',
    timezones: ['America/Santo_Domingo'],
  },
  {
    name: 'Ecuador',
    code: 'EC',
    currency: 'United States Dollar',
    abbreviation: 'USD',
    locale: 'es-EC',
    symbol: '$',
    timezones: ['America/Guayaquil'],
  },
  {
    name: 'Egypt',
    code: 'EG',
    currency: 'Egyptian Pound',
    abbreviation: 'EGP',
    locale: 'ar-EG',
    symbol: 'ج.م',
    timezones: ['Africa/Cairo'],
  },
  {
    name: 'El Salvador',
    code: 'SV',
    currency: 'United States Dollar',
    abbreviation: 'USD',
    locale: 'es-SV',
    symbol: '$',
    timezones: ['America/El_Salvador'],
  },
  {
    name: 'Estonia',
    code: 'EE',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'et-EE',
    symbol: '€',
    timezones: ['Europe/Tallinn'],
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    currency: 'Ethiopian Birr',
    abbreviation: 'ETB',
    locale: 'am-ET',
    symbol: 'Br',
    timezones: ['Africa/Addis_Ababa'],
  },
  {
    name: 'Fiji',
    code: 'FJ',
    currency: 'Fijian Dollar',
    abbreviation: 'FJD',
    locale: 'en-FJ',
    symbol: '$',
    timezones: ['Pacific/Fiji'],
  },
  {
    name: 'Finland',
    code: 'FI',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'fi-FI',
    symbol: '€',
    timezones: ['Europe/Helsinki'],
  },
  {
    name: 'France',
    code: 'FR',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'fr-FR',
    symbol: '€',
    timezones: ['Europe/Paris'],
  },
  {
    name: 'Gabon',
    code: 'GA',
    currency: 'Central African CFA Franc',
    abbreviation: 'XAF',
    locale: 'fr-GA',
    symbol: 'FCFA',
    timezones: ['Africa/Libreville'],
  },
  {
    name: 'Gambia',
    code: 'GM',
    currency: 'Gambian Dalasi',
    abbreviation: 'GMD',
    locale: 'en-GM',
    symbol: 'D',
    timezones: ['Africa/Banjul'],
  },
  {
    name: 'Georgia',
    code: 'GE',
    currency: 'Georgian Lari',
    abbreviation: 'GEL',
    locale: 'ka-GE',
    symbol: '₾',
    timezones: ['Asia/Tbilisi'],
  },
  {
    name: 'Germany',
    code: 'DE',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'de-DE',
    symbol: '€',
    timezones: ['Europe/Berlin', 'Europe/Busingen'],
  },
  {
    name: 'Ghana',
    code: 'GH',
    currency: 'Ghanaian Cedi',
    abbreviation: 'GHS',
    locale: 'en-GH',
    symbol: '₵',
    timezones: ['Africa/Accra'],
  },
  {
    name: 'Greece',
    code: 'GR',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'el-GR',
    symbol: '€',
    timezones: ['Europe/Athens'],
  },
  {
    name: 'Grenada',
    code: 'GD',
    currency: 'East Caribbean Dollar',
    abbreviation: 'XCD',
    locale: 'en-GD',
    symbol: '$',
    timezones: ['America/Grenada'],
  },
  {
    name: 'Guatemala',
    code: 'GT',
    currency: 'Guatemalan Quetzal',
    abbreviation: 'GTQ',
    locale: 'es-GT',
    symbol: 'Q',
    timezones: ['America/Guatemala'],
  },
  {
    name: 'Guinea',
    code: 'GN',
    currency: 'Guinean Franc',
    abbreviation: 'GNF',
    locale: 'fr-GN',
    symbol: 'FG',
    timezones: ['Africa/Conakry'],
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    currency: 'West African CFA Franc',
    abbreviation: 'XOF',
    locale: 'pt-GW',
    symbol: 'CFA',
    timezones: ['Africa/Bissau'],
  },
  {
    name: 'Guyana',
    code: 'GY',
    currency: 'Guyanese Dollar',
    abbreviation: 'GYD',
    locale: 'en-GY',
    symbol: '$',
    timezones: ['America/Guyana'],
  },
  {
    name: 'Haiti',
    code: 'HT',
    currency: 'Haitian Gourde',
    abbreviation: 'HTG',
    locale: 'ht-HT',
    symbol: 'G',
    timezones: ['America/Port-au-Prince'],
  },
  {
    name: 'Honduras',
    code: 'HN',
    currency: 'Honduran Lempira',
    abbreviation: 'HNL',
    locale: 'es-HN',
    symbol: 'L',
    timezones: ['America/Tegucigalpa'],
  },
  {
    name: 'Hungary',
    code: 'HU',
    currency: 'Hungarian Forint',
    abbreviation: 'HUF',
    locale: 'hu-HU',
    symbol: 'Ft',
    timezones: ['Europe/Budapest'],
  },
  {
    name: 'Iceland',
    code: 'IS',
    currency: 'Icelandic Króna',
    abbreviation: 'ISK',
    locale: 'is-IS',
    symbol: 'kr',
    timezones: ['Atlantic/Reykjavik'],
  },
  {
    name: 'India',
    code: 'IN',
    currency: 'Indian Rupee',
    abbreviation: 'INR',
    locale: 'hi-IN',
    symbol: '₹',
    timezones: ['Asia/Kolkata'],
  },
  {
    name: 'Indonesia',
    code: 'ID',
    currency: 'Indonesian Rupiah',
    abbreviation: 'IDR',
    locale: 'id-ID',
    symbol: 'Rp',
    timezones: ['Asia/Jakarta', 'Asia/Jayapura', 'Asia/Makassar', 'Asia/Pontianak'],
  },
  {
    name: 'Iran',
    code: 'IR',
    currency: 'Iranian Rial',
    abbreviation: 'IRR',
    locale: 'fa-IR',
    symbol: '﷼',
    timezones: ['Asia/Tehran'],
  },
  {
    name: 'Iraq',
    code: 'IQ',
    currency: 'Iraqi Dinar',
    abbreviation: 'IQD',
    locale: 'ar-IQ',
    symbol: 'ع.د',
    timezones: ['Asia/Baghdad'],
  },
  {
    name: 'Ireland',
    code: 'IE',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'en-IE',
    symbol: '€',
    timezones: ['Europe/Dublin'],
  },
  {
    name: 'Israel',
    code: 'IL',
    currency: 'Israeli New Shekel',
    abbreviation: 'ILS',
    locale: 'he-IL',
    symbol: '₪',
    timezones: ['Asia/Jerusalem'],
  },
  {
    name: 'Italy',
    code: 'IT',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'it-IT',
    symbol: '€',
    timezones: ['Europe/Rome'],
  },
  {
    name: 'Jamaica',
    code: 'JM',
    currency: 'Jamaican Dollar',
    abbreviation: 'JMD',
    locale: 'en-JM',
    symbol: 'J$',
    timezones: ['America/Jamaica'],
  },
  {
    name: 'Japan',
    code: 'JP',
    currency: 'Japanese Yen',
    abbreviation: 'JPY',
    locale: 'ja-JP',
    symbol: '¥',
    timezones: ['Asia/Tokyo'],
  },
  {
    name: 'Jordan',
    code: 'JO',
    currency: 'Jordanian Dinar',
    abbreviation: 'JOD',
    locale: 'ar-JO',
    symbol: 'د.ا',
    timezones: ['Asia/Amman'],
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    currency: 'Kazakhstani Tenge',
    abbreviation: 'KZT',
    locale: 'kk-KZ',
    symbol: '₸',
    timezones: [
      'Asia/Almaty',
      'Asia/Qyzylorda',
      'Asia/Aqtobe',
      'Asia/Aqtau',
      'Asia/Atyrau',
      'Asia/Oral',
    ],
  },
  {
    name: 'Kenya',
    code: 'KE',
    currency: 'Kenyan Shilling',
    abbreviation: 'KES',
    locale: 'sw-KE',
    symbol: 'KSh',
    timezones: ['Africa/Nairobi'],
  },
  {
    name: 'Kiribati',
    code: 'KI',
    currency: 'Australian Dollar',
    abbreviation: 'AUD',
    locale: 'en-KI',
    symbol: '$',
    timezones: ['Pacific/Tarawa', 'Pacific/Enderbury', 'Pacific/Kiritimati'],
  },
  {
    name: 'Kuwait',
    code: 'KW',
    currency: 'Kuwaiti Dinar',
    abbreviation: 'KWD',
    locale: 'ar-KW',
    symbol: 'د.ك',
    timezones: ['Asia/Kuwait'],
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    currency: 'Kyrgyzstani Som',
    abbreviation: 'KGS',
    locale: 'ky-KG',
    symbol: 'с',
    timezones: ['Asia/Bishkek'],
  },
  {
    name: 'Laos',
    code: 'LA',
    currency: 'Lao Kip',
    abbreviation: 'LAK',
    locale: 'lo-LA',
    symbol: '₭',
    timezones: ['Asia/Vientiane'],
  },
  {
    name: 'Latvia',
    code: 'LV',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'lv-LV',
    symbol: '€',
    timezones: ['Europe/Riga'],
  },
  {
    name: 'Lebanon',
    code: 'LB',
    currency: 'Lebanese Pound',
    abbreviation: 'LBP',
    locale: 'ar-LB',
    symbol: 'ل.ل',
    timezones: ['Asia/Beirut'],
  },
  {
    name: 'Lesotho',
    code: 'LS',
    currency: 'Lesotho Loti',
    abbreviation: 'LSL',
    locale: 'st-LS',
    symbol: 'L',
    timezones: ['Africa/Maseru'],
  },
  {
    name: 'Liberia',
    code: 'LR',
    currency: 'Liberian Dollar',
    abbreviation: 'LRD',
    locale: 'en-LR',
    symbol: '$',
    timezones: ['Africa/Monrovia'],
  },
  {
    name: 'Libya',
    code: 'LY',
    currency: 'Libyan Dinar',
    abbreviation: 'LYD',
    locale: 'ar-LY',
    symbol: 'ل.د',
    timezones: ['Africa/Tripoli'],
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    currency: 'Swiss Franc',
    abbreviation: 'CHF',
    locale: 'de-LI',
    symbol: 'CHF',
    timezones: ['Europe/Vaduz'],
  },
  {
    name: 'Lithuania',
    code: 'LT',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'lt-LT',
    symbol: '€',
    timezones: ['Europe/Vilnius'],
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'fr-LU',
    symbol: '€',
    timezones: ['Europe/Luxembourg'],
  },
  {
    name: 'Madagascar',
    code: 'MG',
    currency: 'Malagasy Ariary',
    abbreviation: 'MGA',
    locale: 'mg-MG',
    symbol: 'Ar',
    timezones: ['Africa/Antananarivo'],
  },
  {
    name: 'Malawi',
    code: 'MW',
    currency: 'Malawian Kwacha',
    abbreviation: 'MWK',
    locale: 'ny-MW',
    symbol: 'MK',
    timezones: ['Africa/Blantyre'],
  },
  {
    name: 'Malaysia',
    code: 'MY',
    currency: 'Malaysian Ringgit',
    abbreviation: 'MYR',
    locale: 'ms-MY',
    symbol: 'RM',
    timezones: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
  },
  {
    name: 'Maldives',
    code: 'MV',
    currency: 'Maldivian Rufiyaa',
    abbreviation: 'MVR',
    locale: 'dv-MV',
    symbol: '.ރ',
    timezones: ['Indian/Maldives'],
  },
  {
    name: 'Mali',
    code: 'ML',
    currency: 'West African CFA Franc',
    abbreviation: 'XOF',
    locale: 'fr-ML',
    symbol: 'CFA',
    timezones: ['Africa/Bamako'],
  },
  {
    name: 'Malta',
    code: 'MT',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'mt-MT',
    symbol: '€',
    timezones: ['Europe/Malta'],
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    currency: 'United States Dollar',
    abbreviation: 'USD',
    locale: 'mh-MH',
    symbol: '$',
    timezones: ['Pacific/Majuro', 'Pacific/Kwajalein'],
  },
  {
    name: 'Mauritania',
    code: 'MR',
    currency: 'Mauritanian Ouguiya',
    abbreviation: 'MRU',
    locale: 'ar-MR',
    symbol: 'UM',
    timezones: ['Africa/Nouakchott'],
  },
  {
    name: 'Mauritius',
    code: 'MU',
    currency: 'Mauritian Rupee',
    abbreviation: 'MUR',
    locale: 'en-MU',
    symbol: '₨',
    timezones: ['Indian/Mauritius'],
  },
  {
    name: 'Mexico',
    code: 'MX',
    currency: 'Mexican Peso',
    abbreviation: 'MXN',
    locale: 'es-MX',
    symbol: '$',
    timezones: [
      'America/Mexico_City',
      'America/Monterrey',
      'America/Tijuana',
      'America/Chihuahua',
      'America/Hermosillo',
      'America/Ojinaga',
      'America/Mazatlan',
    ],
  },
  {
    name: 'Micronesia',
    code: 'FM',
    currency: 'United States Dollar',
    abbreviation: 'USD',
    locale: 'en-FM',
    symbol: '$',
    timezones: ['Pacific/Chuuk', 'Pacific/Pohnpei', 'Pacific/Kosrae'],
  },
  {
    name: 'Moldova',
    code: 'MD',
    currency: 'Moldovan Leu',
    abbreviation: 'MDL',
    locale: 'ro-MD',
    symbol: 'L',
    timezones: ['Europe/Chisinau'],
  },
  {
    name: 'Monaco',
    code: 'MC',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'fr-MC',
    symbol: '€',
    timezones: ['Europe/Monaco'],
  },
  {
    name: 'Mongolia',
    code: 'MN',
    currency: 'Mongolian Tögrög',
    abbreviation: 'MNT',
    locale: 'mn-MN',
    symbol: '₮',
    timezones: ['Asia/Ulaanbaatar', 'Asia/Hovd', 'Asia/Choibalsan'],
  },
  {
    name: 'Montenegro',
    code: 'ME',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'sr-ME',
    symbol: '€',
    timezones: ['Europe/Podgorica'],
  },
  {
    name: 'Morocco',
    code: 'MA',
    currency: 'Moroccan Dirham',
    abbreviation: 'MAD',
    locale: 'ar-MA',
    symbol: 'د.م.',
    timezones: ['Africa/Casablanca'],
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    currency: 'Mozambican Metical',
    abbreviation: 'MZN',
    locale: 'pt-MZ',
    symbol: 'MT',
    timezones: ['Africa/Maputo'],
  },
  {
    name: 'Myanmar (Burma)',
    code: 'MM',
    currency: 'Myanmar Kyat',
    abbreviation: 'MMK',
    locale: 'my-MM',
    symbol: 'K',
    timezones: ['Asia/Yangon'],
  },
  {
    name: 'Namibia',
    code: 'NA',
    currency: 'Namibian Dollar',
    abbreviation: 'NAD',
    locale: 'en-NA',
    symbol: '$',
    timezones: ['Africa/Windhoek'],
  },
  {
    name: 'Nauru',
    code: 'NR',
    currency: 'Australian Dollar',
    abbreviation: 'AUD',
    locale: 'na-NR',
    symbol: '$',
    timezones: ['Pacific/Nauru'],
  },
  {
    name: 'Nepal',
    code: 'NP',
    currency: 'Nepalese Rupee',
    abbreviation: 'NPR',
    locale: 'ne-NP',
    symbol: '₨',
    timezones: ['Asia/Kathmandu'],
  },
  {
    name: 'Netherlands',
    code: 'NL',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'nl-NL',
    symbol: '€',
    timezones: ['Europe/Amsterdam'],
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    currency: 'New Zealand Dollar',
    abbreviation: 'NZD',
    locale: 'en-NZ',
    symbol: '$',
    timezones: ['Pacific/Auckland', 'Pacific/Chatham'],
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    currency: 'Nicaraguan Córdoba',
    abbreviation: 'NIO',
    locale: 'es-NI',
    symbol: 'C$',
    timezones: ['America/Managua'],
  },
  {
    name: 'Niger',
    code: 'NE',
    currency: 'West African CFA Franc',
    abbreviation: 'XOF',
    locale: 'fr-NE',
    symbol: 'CFA',
    timezones: ['Africa/Niamey'],
  },
  {
    name: 'Nigeria',
    code: 'NG',
    currency: 'Nigerian Naira',
    abbreviation: 'NGN',
    locale: 'en-NG',
    symbol: '₦',
    timezones: ['Africa/Lagos'],
  },
  {
    name: 'North Korea',
    code: 'KP',
    currency: 'North Korean Won',
    abbreviation: 'KPW',
    locale: 'ko-KP',
    symbol: '₩',
    timezones: ['Asia/Pyongyang'],
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    currency: 'Macedonian Denar',
    abbreviation: 'MKD',
    locale: 'mk-MK',
    symbol: 'ден',
    timezones: ['Europe/Skopje'],
  },
  {
    name: 'Norway',
    code: 'NO',
    currency: 'Norwegian Krone',
    abbreviation: 'NOK',
    locale: 'nb-NO',
    symbol: 'kr',
    timezones: ['Europe/Oslo'],
  },
  {
    name: 'Oman',
    code: 'OM',
    currency: 'Omani Rial',
    abbreviation: 'OMR',
    locale: 'ar-OM',
    symbol: 'ر.ع.',
    timezones: ['Asia/Muscat'],
  },
  {
    name: 'Pakistan',
    code: 'PK',
    currency: 'Pakistani Rupee',
    abbreviation: 'PKR',
    locale: 'ur-PK',
    symbol: '₨',
    timezones: ['Asia/Karachi'],
  },
  {
    name: 'Palau',
    code: 'PW',
    currency: 'United States Dollar',
    abbreviation: 'USD',
    locale: 'pau-PW',
    symbol: '$',
    timezones: ['Pacific/Palau'],
  },
  {
    name: 'Panama',
    code: 'PA',
    currency: 'Panamanian Balboa',
    abbreviation: 'PAB',
    locale: 'es-PA',
    symbol: 'B/.',
    timezones: ['America/Panama'],
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    currency: 'Papua New Guinean Kina',
    abbreviation: 'PGK',
    locale: 'en-PG',
    symbol: 'K',
    timezones: ['Pacific/Port_Moresby'],
  },
  {
    name: 'Paraguay',
    code: 'PY',
    currency: 'Paraguayan Guaraní',
    abbreviation: 'PYG',
    locale: 'es-PY',
    symbol: '₲',
    timezones: ['America/Asuncion'],
  },
  {
    name: 'Peru',
    code: 'PE',
    currency: 'Peruvian Sol',
    abbreviation: 'PEN',
    locale: 'es-PE',
    symbol: 'S/.',
    timezones: ['America/Lima'],
  },
  {
    name: 'Philippines',
    code: 'PH',
    currency: 'Philippine Peso',
    abbreviation: 'PHP',
    locale: 'fil-PH',
    symbol: '₱',
    timezones: ['Asia/Manila'],
  },
  {
    name: 'Poland',
    code: 'PL',
    currency: 'Polish Złoty',
    abbreviation: 'PLN',
    locale: 'pl-PL',
    symbol: 'zł',
    timezones: ['Europe/Warsaw'],
  },
  {
    name: 'Portugal',
    code: 'PT',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'pt-PT',
    symbol: '€',
    timezones: ['Europe/Lisbon', 'Atlantic/Madeira', 'Atlantic/Azores'],
  },
  {
    name: 'Qatar',
    code: 'QA',
    currency: 'Qatari Riyal',
    abbreviation: 'QAR',
    locale: 'ar-QA',
    symbol: 'ر.ق',
    timezones: ['Asia/Qatar'],
  },
  {
    name: 'Romania',
    code: 'RO',
    currency: 'Romanian Leu',
    abbreviation: 'RON',
    locale: 'ro-RO',
    symbol: 'lei',
    timezones: ['Europe/Bucharest'],
  },
  {
    name: 'Russia',
    code: 'RU',
    currency: 'Russian Ruble',
    abbreviation: 'RUB',
    locale: 'ru-RU',
    symbol: '₽',
    timezones: [
      'Europe/Moscow',
      'Europe/Kaliningrad',
      'Europe/Volgograd',
      'Europe/Samara',
      'Europe/Kirov',
      'Europe/Astrakhan',
      'Europe/Ulyanovsk',
      'Europe/Saratov',
      'Europe/Perm',
      'Europe/Orenburg',
      'Europe/Yekaterinburg',
      'Asia/Omsk',
      'Asia/Novosibirsk',
      'Asia/Barnaul',
      'Asia/Tomsk',
      'Asia/Krasnoyarsk',
      'Asia/Irkutsk',
      'Asia/Yakutsk',
      'Asia/Khandyga',
      'Asia/Vladivostok',
      'Asia/Ust-Nera',
      'Asia/Magadan',
      'Asia/Sakhalin',
      'Asia/Srednekolymsk',
      'Asia/Kamchatka',
      'Asia/Anadyr',
    ],
  },
  {
    name: 'Rwanda',
    code: 'RW',
    currency: 'Rwandan Franc',
    abbreviation: 'RWF',
    locale: 'rw-RW',
    symbol: 'FRw',
    timezones: ['Africa/Kigali'],
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    currency: 'East Caribbean Dollar',
    abbreviation: 'XCD',
    locale: 'en-KN',
    symbol: '$',
    timezones: ['America/St_Kitts'],
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    currency: 'East Caribbean Dollar',
    abbreviation: 'XCD',
    locale: 'en-LC',
    symbol: '$',
    timezones: ['America/St_Lucia'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    currency: 'East Caribbean Dollar',
    abbreviation: 'XCD',
    locale: 'en-VC',
    symbol: '$',
    timezones: ['America/St_Vincent'],
  },
  {
    name: 'Samoa',
    code: 'WS',
    currency: 'Samoan Tala',
    abbreviation: 'WST',
    locale: 'sm-WS',
    symbol: 'T',
    timezones: ['Pacific/Apia'],
  },
  {
    name: 'San Marino',
    code: 'SM',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'it-SM',
    symbol: '€',
    timezones: ['Europe/San_Marino'],
  },
  {
    name: 'São Tomé and Príncipe',
    code: 'ST',
    currency: 'São Tomé and Príncipe Dobra',
    abbreviation: 'STN',
    locale: 'pt-ST',
    symbol: 'Db',
    timezones: ['Africa/Sao_Tome'],
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    currency: 'Saudi Riyal',
    abbreviation: 'SAR',
    locale: 'ar-SA',
    symbol: 'ر.س',
    timezones: ['Asia/Riyadh'],
  },
  {
    name: 'Senegal',
    code: 'SN',
    currency: 'West African CFA Franc',
    abbreviation: 'XOF',
    locale: 'fr-SN',
    symbol: 'CFA',
    timezones: ['Africa/Dakar'],
  },
  {
    name: 'Serbia',
    code: 'RS',
    currency: 'Serbian Dinar',
    abbreviation: 'RSD',
    locale: 'sr-RS',
    symbol: 'дин.',
    timezones: ['Europe/Belgrade'],
  },
  {
    name: 'Seychelles',
    code: 'SC',
    currency: 'Seychellois Rupee',
    abbreviation: 'SCR',
    locale: 'en-SC',
    symbol: '₨',
    timezones: ['Indian/Mahe'],
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    currency: 'Sierra Leonean Leone',
    abbreviation: 'SLE',
    locale: 'en-SL',
    symbol: 'Le',
    timezones: ['Africa/Freetown'],
  },
  {
    name: 'Singapore',
    code: 'SG',
    currency: 'Singapore Dollar',
    abbreviation: 'SGD',
    locale: 'en-SG',
    symbol: '$',
    timezones: ['Asia/Singapore'],
  },
  {
    name: 'Slovakia',
    code: 'SK',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'sk-SK',
    symbol: '€',
    timezones: ['Europe/Bratislava'],
  },
  {
    name: 'Slovenia',
    code: 'SI',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'sl-SI',
    symbol: '€',
    timezones: ['Europe/Ljubljana'],
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    currency: 'Solomon Islands Dollar',
    abbreviation: 'SBD',
    locale: 'en-SB',
    symbol: '$',
    timezones: ['Pacific/Guadalcanal'],
  },
  {
    name: 'Somalia',
    code: 'SO',
    currency: 'Somali Shilling',
    abbreviation: 'SOS',
    locale: 'so-SO',
    symbol: 'Sh',
    timezones: ['Africa/Mogadishu'],
  },
  {
    name: 'South Africa',
    code: 'ZA',
    currency: 'South African Rand',
    abbreviation: 'ZAR',
    locale: 'en-ZA',
    symbol: 'R',
    timezones: ['Africa/Johannesburg'],
  },
  {
    name: 'South Korea',
    code: 'KR',
    currency: 'South Korean Won',
    abbreviation: 'KRW',
    locale: 'ko-KR',
    symbol: '₩',
    timezones: ['Asia/Seoul'],
  },
  {
    name: 'South Sudan',
    code: 'SS',
    currency: 'South Sudanese Pound',
    abbreviation: 'SSP',
    locale: 'en-SS',
    symbol: '£',
    timezones: ['Africa/Juba'],
  },
  {
    name: 'Spain',
    code: 'ES',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'es-ES',
    symbol: '€',
    timezones: ['Europe/Madrid', 'Africa/Ceuta', 'Atlantic/Canary'],
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    currency: 'Sri Lankan Rupee',
    abbreviation: 'LKR',
    locale: 'si-LK',
    symbol: '₨',
    timezones: ['Asia/Colombo'],
  },
  {
    name: 'Sudan',
    code: 'SD',
    currency: 'Sudanese Pound',
    abbreviation: 'SDG',
    locale: 'ar-SD',
    symbol: 'ج.س.',
    timezones: ['Africa/Khartoum'],
  },
  {
    name: 'Suriname',
    code: 'SR',
    currency: 'Surinamese Dollar',
    abbreviation: 'SRD',
    locale: 'nl-SR',
    symbol: '$',
    timezones: ['America/Paramaribo'],
  },
  {
    name: 'Sweden',
    code: 'SE',
    currency: 'Swedish Krona',
    abbreviation: 'SEK',
    locale: 'sv-SE',
    symbol: 'kr',
    timezones: ['Europe/Stockholm'],
  },
  {
    name: 'Switzerland',
    code: 'CH',
    currency: 'Swiss Franc',
    abbreviation: 'CHF',
    locale: 'de-CH',
    symbol: 'CHF',
    timezones: ['Europe/Zurich'],
  },
  {
    name: 'Syria',
    code: 'SY',
    currency: 'Syrian Pound',
    abbreviation: 'SYP',
    locale: 'ar-SY',
    symbol: '£',
    timezones: ['Asia/Damascus'],
  },
  {
    name: 'Taiwan',
    code: 'TW',
    currency: 'New Taiwan Dollar',
    abbreviation: 'TWD',
    locale: 'zh-TW',
    symbol: 'NT$',
    timezones: ['Asia/Taipei'],
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    currency: 'Tajikistani Somoni',
    abbreviation: 'TJS',
    locale: 'tg-TJ',
    symbol: 'ЅМ',
    timezones: ['Asia/Dushanbe'],
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    currency: 'Tanzanian Shilling',
    abbreviation: 'TZS',
    locale: 'sw-TZ',
    symbol: 'TSh',
    timezones: ['Africa/Dar_es_Salaam'],
  },
  {
    name: 'Thailand',
    code: 'TH',
    currency: 'Thai Baht',
    abbreviation: 'THB',
    locale: 'th-TH',
    symbol: '฿',
    timezones: ['Asia/Bangkok'],
  },
  {
    name: 'Togo',
    code: 'TG',
    currency: 'West African CFA Franc',
    abbreviation: 'XOF',
    locale: 'fr-TG',
    symbol: 'CFA',
    timezones: ['Africa/Lome'],
  },
  {
    name: 'Tonga',
    code: 'TO',
    currency: 'Tongan Paʻanga',
    abbreviation: 'TOP',
    locale: 'to-TO',
    symbol: 'T$',
    timezones: ['Pacific/Tongatapu'],
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    currency: 'Trinidad and Tobago Dollar',
    abbreviation: 'TTD',
    locale: 'en-TT',
    symbol: 'TT$',
    timezones: ['America/Port_of_Spain'],
  },
  {
    name: 'Tunisia',
    code: 'TN',
    currency: 'Tunisian Dinar',
    abbreviation: 'TND',
    locale: 'ar-TN',
    symbol: 'د.ت',
    timezones: ['Africa/Tunis'],
  },
  {
    name: 'Turkey',
    code: 'TR',
    currency: 'Turkish Lira',
    abbreviation: 'TRY',
    locale: 'tr-TR',
    symbol: '₺',
    timezones: ['Europe/Istanbul'],
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    currency: 'Turkmenistan Manat',
    abbreviation: 'TMT',
    locale: 'tk-TM',
    symbol: 'm',
    timezones: ['Asia/Ashgabat'],
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    currency: 'Australian Dollar',
    abbreviation: 'AUD',
    locale: 'tvl-TV',
    symbol: '$',
    timezones: ['Pacific/Funafuti'],
  },
  {
    name: 'Uganda',
    code: 'UG',
    currency: 'Ugandan Shilling',
    abbreviation: 'UGX',
    locale: 'sw-UG',
    symbol: 'USh',
    timezones: ['Africa/Kampala'],
  },
  {
    name: 'Ukraine',
    code: 'UA',
    currency: 'Ukrainian Hryvnia',
    abbreviation: 'UAH',
    locale: 'uk-UA',
    symbol: '₴',
    timezones: ['Europe/Kyiv', 'Europe/Uzhgorod', 'Europe/Zaporozhye'],
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    currency: 'United Arab Emirates Dirham',
    abbreviation: 'AED',
    locale: 'ar-AE',
    symbol: 'د.إ',
    timezones: ['Asia/Dubai'],
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    currency: 'Pound Sterling',
    abbreviation: 'GBP',
    locale: 'en-GB',
    symbol: '£',
    timezones: ['Europe/London'],
  },
  {
    name: 'United States Of America',
    code: 'US',
    currency: 'United States Dollar',
    abbreviation: 'USD',
    locale: 'en-US',
    symbol: '$',
    timezones: [
      'America/New_York',
      'America/Los_Angeles',
      'America/Chicago',
      'America/Denver',
      'America/Phoenix',
      'America/Anchorage',
      'America/Honolulu',
      'America/Juneau',
      'America/Boise',
      'America/Detroit',
      'America/Miami',
      'America/Puerto_Rico',
      'America/St_Thomas',
    ],
  },
  {
    name: 'Uruguay',
    code: 'UY',
    currency: 'Uruguayan Peso',
    abbreviation: 'UYU',
    locale: 'es-UY',
    symbol: '$U',
    timezones: ['America/Montevideo'],
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    currency: 'Uzbekistani Som',
    abbreviation: 'UZS',
    locale: 'uz-UZ',
    symbol: 'лв',
    timezones: ['Asia/Tashkent', 'Asia/Samarkand'],
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    currency: 'Vanuatu Vatu',
    abbreviation: 'VUV',
    locale: 'bi-VU',
    symbol: 'VT',
    timezones: ['Pacific/Efate'],
  },
  {
    name: 'Vatican City',
    code: 'VA',
    currency: 'Euro',
    abbreviation: 'EUR',
    locale: 'it-VA',
    symbol: '€',
    timezones: ['Europe/Vatican'],
  },
  {
    name: 'Venezuela',
    code: 'VE',
    currency: 'Venezuelan Bolívar',
    abbreviation: 'VES',
    locale: 'es-VE',
    symbol: 'Bs.',
    timezones: ['America/Caracas'],
  },
  {
    name: 'Vietnam',
    code: 'VN',
    currency: 'Vietnamese Đồng',
    abbreviation: 'VND',
    locale: 'vi-VN',
    symbol: '₫',
    timezones: ['Asia/Ho_Chi_Minh'],
  },
  {
    name: 'Yemen',
    code: 'YE',
    currency: 'Yemeni Rial',
    abbreviation: 'YER',
    locale: 'ar-YE',
    symbol: '﷼',
    timezones: ['Asia/Aden'],
  },
  {
    name: 'Zambia',
    code: 'ZM',
    currency: 'Zambian Kwacha',
    abbreviation: 'ZMW',
    locale: 'en-ZM',
    symbol: 'ZK',
    timezones: ['Africa/Lusaka'],
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    currency: 'Zimbabwean Dollar',
    abbreviation: 'ZWL',
    locale: 'en-ZW',
    symbol: 'Z$',
    timezones: ['Africa/Harare'],
  },
];

export default countries;

const getCurrencies = countries => {
  const currencyMap = new Map();

  countries.forEach(({currency, abbreviation}) => {
    if (!currencyMap.has(abbreviation)) {
      currencyMap.set(abbreviation, currency);
    }
  });

  return Array.from(currencyMap.entries()).map(([abbreviation, currency]) => ({
    currency,
    abbreviation,
  }));
};

export const currencies = getCurrencies(countries);
