export const demoviolationTableData = {
  page1: [
    {
      id: 'V-1431',
      date: '2025-04-14',
      unitResident: '12-B / John Smith',
      issue: 'Trash Can Left Out',
      status: 'In Cure',
    },
    {
      id: 'V-1426',
      date: '2025-04-13',
      unitResident: '7-A / Emily Johnson',
      issue: 'Unauthorised Paint Color',
      status: 'In Cure',
    },
    {
      id: 'V-1425',
      date: '2025-04-08',
      unitResident: '45-G / Megan Clark',
      issue: 'Late Night Noise',
      status: 'Fined',
    },
    {
      id: 'V-1411',
      date: '2025-04-02',
      unitResident: 'PH-2 / Andrew Thomas',
      issue: 'Trash Can Left Out',
      status: 'Escalated',
    },
    {
      id: 'V-1404',
      date: '2025-04-01',
      unitResident: '12-B / John Smith',
      issue: 'Trash Can Left Out',
      status: 'Closed',
    },
    {
      id: 'V-1401',
      date: '2025-03-22',
      unitResident: '2-09 / Lauren Evans',
      issue: 'Unauthorised Paint Color',
      status: 'In Cure',
    },
    {
      id: 'V-1390',
      date: '2025-03-20',
      unitResident: 'PH-2 / Andrew Thomas',
      issue: 'Parking Violation',
      status: 'In Cure',
    },
    {
      id: 'V-1387',
      date: '2025-03-18',
      unitResident: '21-C / Jason Miller',
      issue: 'Unapproved Architectural Change',
      status: 'Escalated',
    },
    {
      id: 'V-1376',
      date: '2025-03-15',
      unitResident: '12-G / Adams Meds',
      issue: 'Excessive Noise',
      status: 'Late to cure',
    },
    {
      id: 'V-1375',
      date: '2025-03-14',
      unitResident: '5-D / Olivia Garcia',
      issue: 'Improper Pet Waste Disposal',
      status: 'Fined',
    },
  ],
  page2: [
    {
      id: 'V-1370',
      date: '2025-03-10',
      unitResident: '18-A / Noah Martinez',
      issue: 'Balcony Clutter',
      status: 'In Cure',
    },
    {
      id: 'V-1368',
      date: '2025-03-09',
      unitResident: '2-09 / Lauren Evans',
      issue: 'Late Night Noise',
      status: 'Closed',
    },
    {
      id: 'V-1365',
      date: '2025-03-05',
      unitResident: 'PH-1 / Samantha White',
      issue: 'Smoking in Common Area',
      status: 'Escalated',
    },
    {
      id: 'V-1362',
      date: '2025-03-02',
      unitResident: '7-A / Emily Johnson',
      issue: 'Parking Violation',
      status: 'Fined',
    },
    {
      id: 'V-1359',
      date: '2025-02-28',
      unitResident: '22-F / David Rodriguez',
      issue: 'Unauthorised Guest Parking',
      status: 'In Cure',
    },
    {
      id: 'V-1355',
      date: '2025-02-25',
      unitResident: '12-B / John Smith',
      issue: 'Damage to Common Property',
      status: 'Escalated',
    },
    {
      id: 'V-1351',
      date: '2025-02-20',
      unitResident: '3-C / Chloe Wilson',
      issue: 'Leaking Air Conditioner',
      status: 'Closed',
    },
    {
      id: 'V-1348',
      date: '2025-02-18',
      unitResident: '15-E / James Anderson',
      issue: 'Trash Can Left Out',
      status: 'Late to cure',
    },
    {
      id: 'V-1345',
      date: '2025-02-15',
      unitResident: '9-H / Isabella Moore',
      issue: 'Unregistered Pet',
      status: 'In Cure',
    },
    {
      id: 'V-1340',
      date: '2025-02-11',
      unitResident: 'PH-2 / Andrew Thomas',
      issue: 'Excessive Noise',
      status: 'Fined',
    },
  ],
  page3: [
    {
      id: 'V-1337',
      date: '2025-02-08',
      unitResident: '6-A / Benjamin Taylor',
      issue: 'Blocked Fire Exit',
      status: 'Escalated',
    },
    {
      id: 'V-1333',
      date: '2025-02-05',
      unitResident: '19-D / Mia Martin',
      issue: 'Improper Balcony Usage',
      status: 'Closed',
    },
    {
      id: 'V-1330',
      date: '2025-02-01',
      unitResident: '12-G / Adams Meds',
      issue: 'Parking Violation',
      status: 'In Cure',
    },
    {
      id: 'V-1326',
      date: '2025-01-28',
      unitResident: '21-C / Jason Miller',
      issue: 'Late Night Noise',
      status: 'Late to cure',
    },
    {
      id: 'V-1322',
      date: '2025-01-24',
      unitResident: '11-B / Sophia Lee',
      issue: 'Unauthorised Alterations',
      status: 'Escalated',
    },
    {
      id: 'V-1319',
      date: '2025-01-20',
      unitResident: '1-F / William Perez',
      issue: 'Trash Can Left Out',
      status: 'Fined',
    },
    {
      id: 'V-1315',
      date: '2025-01-16',
      unitResident: '7-A / Emily Johnson',
      issue: 'Common Area Misuse',
      status: 'In Cure',
    },
    {
      id: 'V-1312',
      date: '2025-01-12',
      unitResident: '14-E / Charlotte Thompson',
      issue: 'Violation of Quiet Hours',
      status: 'Closed',
    },
    {
      id: 'V-1309',
      date: '2025-01-09',
      unitResident: '20-A / Daniel White',
      issue: 'Parking in Fire Lane',
      status: 'Escalated',
    },
    {
      id: 'V-1305',
      date: '2025-01-05',
      unitResident: '8-C / Amelia Harris',
      issue: 'Improper Window Coverings',
      status: 'In Cure',
    },
  ],
  page4: [
    {
      id: 'V-1301',
      date: '2025-01-02',
      unitResident: '12-B / John Smith',
      issue: 'Excessive Noise',
      status: 'Fined',
    },
    {
      id: 'V-1298',
      date: '2024-12-29',
      unitResident: '17-G / Michael Sanchez',
      issue: 'Unattended Delivery Packages',
      status: 'Late to cure',
    },
    {
      id: 'V-1295',
      date: '2024-12-26',
      unitResident: '2-09 / Lauren Evans',
      issue: 'Trash Can Left Out',
      status: 'Closed',
    },
    {
      id: 'V-1291',
      date: '2024-12-22',
      unitResident: '4-D / Evelyn Clark',
      issue: 'Smoking Violation',
      status: 'Escalated',
    },
    {
      id: 'V-1288',
      date: '2024-12-19',
      unitResident: '10-H / Alexander Lewis',
      issue: 'Unauthorised Paint Color',
      status: 'In Cure',
    },
    {
      id: 'V-1284',
      date: '2024-12-15',
      unitResident: 'PH-1 / Samantha White',
      issue: 'Parking Violation',
      status: 'Fined',
    },
    {
      // Added entry 37
      id: 'V-1280',
      date: '2024-12-12',
      unitResident: '23-A / Christopher Hall',
      issue: 'Landscape Damage',
      status: 'Escalated',
    },
    {
      // Added entry 38
      id: 'V-1277',
      date: '2024-12-10',
      unitResident: '16-F / Abigail Young',
      issue: 'Late Night Noise',
      status: 'Late to cure',
    },
    {
      // Added entry 39
      id: 'V-1275',
      date: '2024-12-08',
      unitResident: '9-B / Matthew Allen',
      issue: 'Improper Storage in Common Area',
      status: 'In Cure',
    },
    {
      // Added entry 40
      id: 'V-1272',
      date: '2024-12-05',
      unitResident: '5-D / Olivia Garcia',
      issue: 'Trash Can Left Out',
      status: 'Closed',
    },
  ],
};
