import {
  Drawer,
  DrawerBody,
  DrawerCloseButton,
  DrawerContent,
  DrawerOverlay,
  Flex,
  Image,
  Link,
  ListItem,
  OrderedList,
  Text,
  UnorderedList,
  VStack,
} from '@chakra-ui/react';
import React from 'react';
import check from '../../images/check-circle.svg';
import qrcode from '../../images/app-qrcode.png';

const How2FAWorks = ({drawerModal}) => {
  return (
    <Drawer isOpen={drawerModal?.isOpen} placement="right" onClose={drawerModal?.onClose}>
      <DrawerOverlay />
      <DrawerContent marginTop="65px" py="22px" maxW="400px" overflowY={'scroll'}>
        <DrawerCloseButton />
        {/* <DrawerBody> */}
        <Flex px={'21px'} justify="center" direction="column" gap="10px">
          <Image
            alt=""
            h="36px"
            w="36px"
            borderRadius={'21px'}
            src={check.src}
            border="6px solid rgba(69, 69, 254, 0.10)"
            bg="rgba(69, 69, 254, 0.10)"
          />
          <Text color="#191919" fontWeight={500} fontSize="18px">
            How does 2FA works?
          </Text>
        </Flex>
        <VStack
          px={'21px'}
          mt="20px"
          pt="20px"
          align="stretch"
          spacing={'20px'}
          color="#3D3D3D"
          fontSize={'14px'}
          fontWeight={400}
          bg="#FBFCFC"
        >
          <Text>
            Every time you log in to your Veerge account, you need to provide a second factor of
            authentication (2FA). Authentication apps generate secure, temporary tokens to verify
            your identity when logging in. Unlike text message verification codes, the tokens
            generated by 2FA apps can’t be intercepted by hackers.
          </Text>
          <b>Setting up an authentication app</b>
          <OrderedList>
            <ListItem>
              <Text mb="20px">{`First, you'll need to download a 2FA app.`}</Text>
              <Text>Here are a few:</Text>
              <UnorderedList mb="20px">
                <ListItem mb="20px">
                  Authy (
                  <Link
                    href="https://apps.apple.com/us/app/twilio-authy/id494168017"
                    target="_blank"
                    textDecoration={'underline'}
                  >
                    App Store
                  </Link>{' '}
                  |{' '}
                  <Link
                    href="https://play.google.com/store/apps/details?id=com.authy.authy&hl=en"
                    textDecoration={'underline'}
                    target="_blank"
                  >
                    Google Play
                  </Link>
                  )
                </ListItem>
                <ListItem mb="20px">
                  LastPass Authenticator (
                  <Link
                    href="https://apps.apple.com/us/app/lastpass-authenticator/id1079110004"
                    target="_blank"
                    textDecoration={'underline'}
                  >
                    App Store
                  </Link>{' '}
                  |{' '}
                  <Link
                    href="https://play.google.com/store/apps/details?id=com.lastpass.authenticator&hl=en"
                    target="_blank"
                    textDecoration={'underline'}
                  >
                    Google Play
                  </Link>
                  )
                </ListItem>
                <ListItem>
                  Google Authenticator (
                  <Link
                    href="https://apps.apple.com/us/app/google-authenticator/id388497605"
                    target="_blank"
                    textDecoration={'underline'}
                  >
                    App Store
                  </Link>{' '}
                  |{' '}
                  <Link
                    href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en"
                    target="_blank"
                    textDecoration={'underline'}
                  >
                    Google Play
                  </Link>
                  )
                </ListItem>
              </UnorderedList>
            </ListItem>
            <ListItem mb="20px">
              {`Once you've downloaded an app and set up an account, scan the QR code or enter the key
              code to connect your authentication app with your Veerge account.`}
            </ListItem>
            <ListItem>
              Enter the token generated in the app. New tokens are generated every 30 seconds or so.
            </ListItem>
          </OrderedList>
          <Text mb="20px">This QR code is an example and will not link to your account.</Text>
          <Image alt="" mx="auto" src={qrcode.src} />
          <Text mb="20px">
            {`  Never delete your authentication app from your device. You'll need it to log into your
            Veerge account. If you accidentally delete the app, or get a new device, try logging
            into your authentication app account on the desktop website. Then, change or reset your
            authentication app on your Security Page.`}
          </Text>
        </VStack>
        {/* </DrawerBody> */}
      </DrawerContent>
    </Drawer>
  );
};

export default How2FAWorks;
