import {useState} from 'react';
import Head from 'next/head';
import {AnimatedLoader, LayoutView} from '../../../components';
import Link from 'next/link';
import {Box, Flex, useToast, Stack, Text} from '@chakra-ui/react';
import {useQuery} from '@tanstack/react-query';
import {getEquityOverview} from '../../../apis/account';
import {MatadorCustomTable} from '../../../components/common/Table';
import {FRACTION_AMOUNT_COLUMN} from '../../../constants/accounts/fraction/totalFData';
import fractionData from '../../../constants/accounts/fraction/total_fraction_data';
import BackBtn from '../components/BackBtn';
import PriceBox from '../components/PriceBox';
import Range from '../components/Range';

const Payment = () => {
  const toast = useToast();
  const ACCOUNTEQUITYOVERVIEW = useQuery(['account-purchase'], getEquityOverview);
  const TOTAL_PURCHASES =
    ACCOUNTEQUITYOVERVIEW?.data && ACCOUNTEQUITYOVERVIEW?.data?.data?.pruchases_data;

  return (
    <div className="relative">
      <Head>
        <title>Veerge | Total Fractions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#191919" />
        <Link prefetch={false} rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutView activePage={'account'} />
      <Box px="78px" position="relative" mt="-83vh">
        <Flex w="full" justify="space-between" mb={1}>
          <BackBtn name="Back" />
        </Flex>
        {/* <Range /> */}
        <PriceBox />
        <MatadorCustomTable
          maxW=""
          minW="full"
          COLUMNS={FRACTION_AMOUNT_COLUMN(fractionData)}
          DATA={fractionData}
        />
      </Box>
      {/* )} */}
    </div>
  );
};

export default Payment;
