import Head from 'next/head';
import Link from 'next/link';
import Range from '../components/Range';
import {Box, Flex} from '@chakra-ui/react';
import BackBtn from '../components/BackBtn';
import PriceBox from '../components/PriceBox';
import {useQuery} from '@tanstack/react-query';
import {LayoutView} from '../../../components';
import {getEquityOverview} from '../../../apis/account';
import paymentData from '../../../constants/accounts/payment/total_payment_data';
import {MatadorCustomTable} from '../../../components/common/Table';
import {PAYMENT_COLUMN} from '../../../constants/accounts/payment/totalPPData';

const Payment = () => {
  const ACCOUNTEQUITYOVERVIEW = useQuery(['account-purchase'], getEquityOverview);
  const TOTAL_PURCHASES =
    ACCOUNTEQUITYOVERVIEW?.data && ACCOUNTEQUITYOVERVIEW?.data?.data?.pruchases_data;

  return (
    <div className="relative">
      <Head>
        <title>Veerge | Total Payment Plan List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#191919" />
        <Link prefetch={false} rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutView activePage={'account'} />
      {/* {ACCOUNTEQUITYOVERVIEW.isLoading ? (
				<Flex direction='column' w='full' h='full' justify='center' align='center'>
					<AnimatedLoader />
				</Flex>
			) : ACCOUNTEQUITYOVERVIEW.isError ? (
				toast({
					title: 'An error occured',
					status: 'error',
					duration: 5000,
					isClosable: true,
					position: 'top-right',
				})
			) : ( */}
      <Box px="75px" position="relative" mt="-83vh">
        <Flex w="full" justify="space-between" mb={4}>
          <BackBtn name="Back" />
        </Flex>
        <Range />
        <PriceBox />
        <MatadorCustomTable
          maxW=""
          minW="full"
          COLUMNS={PAYMENT_COLUMN(paymentData)}
          DATA={paymentData}
        />
      </Box>
      {/* )} */}
    </div>
  );
};

export default Payment;
