import React, {useEffect, useState} from 'react';
import {
  AbsoluteCenter,
  Box,
  Button,
  Center,
  HStack,
  Heading,
  Input,
  PinInput,
  PinInputField,
  Stack,
  Text,
  useToast,
} from '@chakra-ui/react';
import {motion} from 'framer-motion';

const inputStyles = {
  fontSize: '35.62px',
  lineHeight: '31.17px',
  color: '#3d3d3d',
  fontWeight: '500',
  border: '1px solid #e5e5e5',
  borderRadius: '11.13px',
  bg: '#fafafa',

  w: '61.22px',

  h: '55.66px',
  textAlign: 'center',
  _focusVisible: {
    outline: 'none',
  },
  _placeholder: {
    color: '#E5E5E5',
  },
};

const VerifyTwoForLogin = ({handleLogin, mutation}) => {
  const [twoFa, setTwoFa] = useState('');
  const isOtpValid = twoFa.length === 6;

  return (
    <Stack
      as={motion.div}
      animate={{
        opacity: 1,
        transition: {
          delay: 0.1,
        },
      }}
      initial={{opacity: 0}}
      spacing={'32px'}
      w="full"
      justify="center"
    >
      <Stack spacing="4px">
        <HStack alignSelf={{base: 'start', md: 'center'}} spacing="8px">
          <Heading
            textAlign={{base: 'start', md: 'center'}}
            fontSize="48px"
            fontWeight="600"
            fontFamily="Neue Haas Grotesk Display Pro"
            color="#191919"
          >
            Two Factor Authentication
          </Heading>
        </HStack>
        <Text
          textAlign={{base: 'start', md: 'center'}}
          fontSize="18px"
          fontFamily="Neue Haas Grotesk Display Pro"
          fontWeight="500"
          color="#525252"
        >
          Enter the 6-digit verification code generated by your Authenticator app to proceed
        </Text>
      </Stack>
      <Stack w="full" as="form" align="center" onSubmit={handleLogin(twoFa)} spacing="32px">
        <HStack maxW="423px" spacing="12.24px">
          <PinInput value={twoFa} onChange={value => setTwoFa(value)} placeholder="0">
            <PinInputField required {...inputStyles} />
            <PinInputField required {...inputStyles} />
            <PinInputField required {...inputStyles} />

            <PinInputField required {...inputStyles} />
            <PinInputField required {...inputStyles} />
            <PinInputField required {...inputStyles} />
          </PinInput>
        </HStack>

        <Button
          variant="filled-radius"
          type="submit"
          isDisabled={!isOtpValid}
          isLoading={mutation.isLoading}
        >
          Proceed
        </Button>
      </Stack>
    </Stack>
  );
};

export default VerifyTwoForLogin;
