import Head from 'next/head';
import Link from 'next/link';
import {fetchAllAccountData} from '../../apis/account';
import {
  Box,
  Text,
  Image,
  Flex,
  useToast,
  Stack,
  useDisclosure,
  AbsoluteCenter,
  useMediaQuery,
  Button,
  Icon,
} from '@chakra-ui/react';
import {useRouter} from 'next/router';
import {useQuery} from '@tanstack/react-query';
import overviewIcon from '/src/images/icons/linearHome.svg';
import walletIcon from '/src/images/icons/wallet.svg';
import {AccountDrawer} from '../../components/Drawers/account';
import {AnimatedLoader} from '../../components/common/loaders';
import {
  FormatToColorfulAdaptiveCurrency,
  FormatToColorfulCurrency,
  formatAmountWithDecimal,
} from '../../utils/formatAmount';
import {LayoutView} from '../../components/PageLayout/LayoutView';
import {AccountTransactionDetails} from '../../components/account/accountTransactionDetails';
import {FaAngleRight} from 'react-icons/fa6';
import DepositDrawer from '../../components/Drawers/depositDrawer';
import Graph from './components/graph';
import {useSmallerLaptopsBreakpoint} from 'ui-lib/ui-lib.hooks';
import {useIsGatewayDisabled} from 'utils/useIsGatewayDisabled';

export default function Account() {
  const toast = useToast();
  const isSmallerLaptop = useSmallerLaptopsBreakpoint();

  const accountModal = useDisclosure();
  const DEPOSIT_DRAWER = useDisclosure();

  const ACCOUNT__DATA = useQuery(['account-data'], () => fetchAllAccountData(''));

  const ACCOUNT__INFO = ACCOUNT__DATA?.data?.data;

  const OVERVIEW_SUMMARY = ACCOUNT__INFO?.overview;
  const USER_WALLET_TOTAL = ACCOUNT__INFO?.wallet_overview?.store_total;
  const AGENT_WALLET_TOTAL = ACCOUNT__INFO?.wallet_overview?.agent_total;
  const [isBelow800] = useMediaQuery('(max-width: 800px)');
  const isGateWayDisabled = useIsGatewayDisabled();

  return (
    <Stack mx="auto" bg="#FAFAFA" h={isSmallerLaptop ? '60vh' : ''}>
      <Head>
        <title>Veerge | Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#191919" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <LayoutView
        maxW="full"
        tabPanelStyle={{px: '0px', pb: '0px'}}
        px="0px"
        pb="30px"
        activePage={'account'}
      >
        {
          <Box
            bg="#FAFAFA"
            mx="auto"
            mt={`clamp(52px,calc(10.4vh + 40px),82px)`}
            maxW="full"
            w="full"
          >
            <main className="text-[#333]">
              <Flex
                px={{base: `16px`, xl: '78px'}}
                direction={{base: `column`, xl: `row`}}
                justify="center"
                gap="25px"
                h={`100%`}
                mt="15px"
              >
                <Graph
                  isAccount
                  outstandingBalance={formatAmountWithDecimal(OVERVIEW_SUMMARY?.total_outstanding)}
                  unprocessedTransactions={
                    ACCOUNT__INFO?.graph_sidebar?.total_unprocessed_transaction
                  }
                />

                <Flex
                  maxH="321px"
                  alignItems="stretch"
                  flex={`407`}
                  gap="24px"
                  direction={{base: 'row', xl: 'column'}}
                >
                  <Box
                    flex={{base: '1', xl: `1`}}
                    bg="#FFFFFF"
                    boxShadow="0px 4px 8px rgba(0, 0, 0, 0.02)"
                    border="1px solid #e4e4e4"
                    borderRadius="16px"
                    h={isGateWayDisabled ? 'full' : 'fit-content'}
                    display="flex"
                    flexDirection="column"
                  >
                    <div className="flex pt-2 h-[50px] border-b border-[#e4e4e7] rounded-t-[16px] bg-[#fbfcfc] flex-row items-center p-2">
                      <Image
                        alt=""
                        src={overviewIcon.src}
                        className="text-[#4545FE] w-8 mt-1 ml-1 h-6"
                      />
                      <Text fontSize="14px" fontWeight={500} className="ml-2 mt-1">
                        Overview
                      </Text>
                    </div>
                    <div
                      className={`grid  h-[100%]  self-stretch items-stretch grid-cols-2 grid-rows-2 gap-[12px]  p-[18px] `}
                    >
                      <div className="rounded-lg border  gap-[8px] border-[#EFEFEF] py-1  mx-auto flex flex-col w-full items-center justify-center px-2">
                        <Text fontSize="11px" color="#52525b" fontWeight="500">
                          Total Assessments
                        </Text>
                        <FormatToColorfulAdaptiveCurrency
                          baseSize={16}
                          fontWeight={600}
                          lens={16}
                          maxSize={16}
                          minSize={10}
                          pow={isBelow800 ? 0.68 : 0.92}
                          decimalStyle={{fontWeight: '600'}}
                          wordBreak="break-word"
                          color={'#333333'}
                          amount={OVERVIEW_SUMMARY?.total_purchases ?? 6764000}
                        />

                        <Button
                          fontSize="12px"
                          fontWeight="500"
                          color="#4545fe"
                          variant="ghost"
                          p="0px"
                          h="fit-content"
                          _hover={{
                            bg: 'transparent',
                          }}
                          rightIcon={<Icon as={FaAngleRight} color="#4545fe" boxSize="10px" />}
                          iconSpacing="0px"
                        >
                          View
                        </Button>
                      </div>
                      <div className="rounded-lg border  gap-[8px] border-[#EFEFEF] py-1  mx-auto flex flex-col w-full items-center justify-center">
                        <Text fontSize="11px" color="#52525b" fontWeight="500">
                          Total Amenities Fees
                        </Text>
                        <FormatToColorfulAdaptiveCurrency
                          baseSize={16}
                          fontWeight={600}
                          lens={16}
                          maxSize={16}
                          minSize={10}
                          wrapper={{mt: '4px'}}
                          pow={isBelow800 ? 0.68 : 0.92}
                          decimalStyle={{fontWeight: '600'}}
                          wordBreak="break-word"
                          color={'#333333'}
                          amount={OVERVIEW_SUMMARY?.escrow ?? 1034470}
                        />
                        <Button
                          fontSize="12px"
                          fontWeight="500"
                          color="#4545fe"
                          variant="ghost"
                          p="0px"
                          h="fit-content"
                          _hover={{
                            bg: 'transparent',
                          }}
                          rightIcon={<Icon as={FaAngleRight} color="#4545fe" boxSize="10px" />}
                          iconSpacing="0px"
                        >
                          View
                        </Button>
                      </div>

                      <div className="rounded-lg border gap-[8px] border-[#EFEFEF] py-1  mx-auto flex flex-col w-full items-center justify-center">
                        <Text fontSize="11px" color="#52525b" fontWeight="500">
                          Violation & Fine Payments
                        </Text>
                        <FormatToColorfulAdaptiveCurrency
                          baseSize={16}
                          fontWeight={600}
                          lens={16}
                          maxSize={16}
                          minSize={10}
                          pow={isBelow800 ? 0.68 : 0.92}
                          decimalStyle={{fontWeight: '600'}}
                          wordBreak="break-word"
                          color={'#333333'}
                          amount={USER_WALLET_TOTAL ?? 864240}
                        />

                        <Button
                          fontSize="12px"
                          fontWeight="500"
                          color="#4545fe"
                          variant="ghost"
                          p="0px"
                          h="fit-content"
                          _hover={{
                            bg: 'transparent',
                          }}
                          rightIcon={<Icon as={FaAngleRight} color="#4545fe" boxSize="10px" />}
                          iconSpacing="0px"
                        >
                          View
                        </Button>
                      </div>
                      <div className="rounded-lg border border-[#EFEFEF] py-1 gap-[8px]  mx-auto flex flex-col w-full items-center justify-center px-2">
                        <Text fontSize="11px" color="#52525b" fontWeight="500">
                          Cap Fee
                        </Text>
                        <FormatToColorfulAdaptiveCurrency
                          baseSize={16}
                          fontWeight={600}
                          lens={16}
                          maxSize={16}
                          minSize={10}
                          pow={isBelow800 ? 0.68 : 0.92}
                          wrapper={{mt: '4px'}}
                          decimalStyle={{fontWeight: '600'}}
                          wordBreak="break-word"
                          color={'#333333'}
                          amount={AGENT_WALLET_TOTAL ?? 4674243}
                        />
                        <Link prefetch={true} href="/capFee">
                          <Button
                            fontSize="12px"
                            fontWeight="500"
                            color="#4545fe"
                            variant="ghost"
                            p="0px"
                            h="fit-content"
                            _hover={{
                              bg: 'transparent',
                            }}
                            rightIcon={<Icon as={FaAngleRight} color="#4545fe" boxSize="10px" />}
                            iconSpacing="0px"
                          >
                            View
                          </Button>
                        </Link>
                      </div>
                    </div>
                  </Box>
                </Flex>
              </Flex>

              <Box mt="30px" />
              <Stack
                w="full"
                direction="row"
                px={{base: `16px`, xl: '78px'}}
                overflowX={{base: `auto`, xl: 'visible'}}
                css={{
                  '::-webkit-scrollbar': {
                    display: 'none',
                  },
                }}
              >
                <AccountTransactionDetails
                  depositsData={ACCOUNT__INFO?.deposits}
                  withdrawalsData={ACCOUNT__INFO?.withdrawals}
                  upcomingDeposits={ACCOUNT__INFO?.upcomings}
                />
              </Stack>
            </main>
          </Box>
        }
        <AccountDrawer drawerModal={accountModal} />
        <DepositDrawer DepositDrawer={DEPOSIT_DRAWER} />
      </LayoutView>
    </Stack>
  );
}
