import React, {useState} from 'react';
import {
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  HStack,
  Heading,
  Text,
  Button,
  useToast,
  Stack,
} from '@chakra-ui/react';
import {OTPInput} from 'chakra-otp-input';
import {useFormik} from 'formik';
import {useMutation, useQueryClient} from '@tanstack/react-query';
import {CreateToast} from '../../../../ui-lib';
import {toastForError} from '../../../../utils/toastForErrors';
import {updateTwoFac} from '../../../../apis/settings';

export const VerifyTwoFa = ({customScrollbarStyles, handleClose, refetch, handleScreen}) => {
  const [twoFaOtp, setTwoFaValue] = useState(null);

  const toast = useToast();

  const queryClient = useQueryClient();
  const toaster = CreateToast();
  const formik = useFormik({
    initialValues: {},
    onSubmit: values => {
      mutateAuth({...values, code: code});
      console.log(JSON.stringify(values));
    },
    validate: values => {
      const errors = {};
      if (!values.code || values.code.length !== 6) {
        errors.code = 'Please Enter 6 Digit Exactly';
      }
      return errors;
    },
    validateOnChange: true,
  });

  const {mutate: mutateAuth, isLoading: isLoadingAuth} = useMutation(
    values => {
      return updateTwoFac(values);
    },
    {
      onSuccess: async res => {
        console.log(res);
        if (res?.data?.status === 'False') {
          toastForError(err, true, toast);
        } else {
          // queryClient.invalidateQueries(['fetchDeveloperProfile']);
          // await queryClient.refetchQueries(['fetchDeveloperProfile']);
          await refetch();
          // toast({
          //   title: 'updated successfully',
          //   description: `Two Factor Authentication enabled
          //       `,
          //   status: 'success',
          //   duration: 8000,
          //   isClosable: true,
          //   position: 'top-right',
          // });
          handleClose();
          toaster('Two Factor Authentication enabled');
        }
      },
      onError: err => {
        return toastForError(err, true, toast);
      },
    }
  );

  const handleVerify = () => {
    return mutateAuth({
      code: twoFaOtp,
      update: true,
    });
  };

  const isValid = twoFaOtp?.length == 6;

  return (
    <>
      <HStack mt="26px" justify="space-between" px="29px" align="center" position="relative">
        <Heading fontWeight="600" fontSize="24px" color="#191919">
          Two factor authentication
        </Heading>
        <ModalCloseButton onClick={handleClose} position="initial" />
      </HStack>
      <ModalBody mt="15px" w="483px" px="29px" py="0px">
        <Stack spacing="48px" w="full" mb="48px">
          <Text fontSize="14px" color="#3D3D3D" fontWeight="300">
            Enter the 6-digit verification code generated by your Authenticator app
          </Text>
          <Stack spacing="8px">
            <OTPInput
              // style={{color: '#191919'}}
              w="full"
              h="55.658px"
              value={twoFaOtp}
              type="number"
              noInputs={6}
              bg="#E5E5E5"
              boxShadow="none"
              color="#333"
              fontSize="28.884px"
              fontWeight="300"
              borderRadius="8px"
              onChange={value => setTwoFaValue(value)}
            />
          </Stack>
        </Stack>
      </ModalBody>

      <ModalFooter p="0px" px="29px" mb="26px">
        <Button
          h="55px"
          color="#fff"
          w="full"
          bg="#4545FE"
          borderRadius="12px"
          fontSize="18px"
          fontWeight="400"
          _hover={{
            opacity: 1,
          }}
          _active={{
            opacity: 1,
          }}
          onClick={handleVerify}
          isLoading={isLoadingAuth}
          isDisabled={!isValid}
        >
          Verify
        </Button>
      </ModalFooter>
    </>
  );
};

export default VerifyTwoFa;
