import {Flex, Spinner, Stack, Text, Box} from '@chakra-ui/react';
import {OTPInput} from 'chakra-otp-input';
import {Button, Form} from 'ui-lib';
import React, {useEffect, useState} from 'react';

const TwoFAForm = ({siginBodyValues, mutation}) => {
  const [code, setCode] = useState(null);
  useEffect(() => {
    code?.length == 6 && mutation.mutate({...siginBodyValues, code: code});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [code]);
  return (
    <div>
      <Stack
        rounded={'xl'}
        px={{base: 4, sm: 6, md: 10}}
        spacing={{base: 8}}
        mx="auto"
        w={{base: 'md', md: '451px'}}
        background="rgba(255, 255, 255, 0.1)"
        boxShadow="0px 8px 48px rgba(0, 0, 0, 0.04)"
        borderRadius="20px"
        className="main-app"
      >
        <Box pt="31px" pb="40px" mx="auto" w="full">
          <Stack spacing="none">
            <Form.Header
              align="start"
              fontSize={'29px'}
              fontWeight={'600'}
              fontFamily={'Euclid Circular B'}
              color="#FFFFFF"
            >
              Two Factor Authentication
            </Form.Header>
            <Form.Description>
              <Text
                w="full"
                mt="12px"
                align="left"
                color="#FFFFFF"
                fontSize={'14px'}
                fontWeight={'400'}
              >
                Enter the 6-digit verification code generated by your Authenticator app to proceed
              </Text>
            </Form.Description>

            <Flex pb="42px" pt="38px" px="1px" justify="center" align="center" w="full">
              <OTPInput
                type="number"
                fontSize={'35.621px'}
                fontWeight={'300'}
                w="full"
                borderRadius="12px"
                border="1px solid #E4E4E4"
                h="55.658px"
                value={code}
                noInputs={6}
                onChange={value => setCode(value)}
                style={{color: '#FFFFFF', backgroundColor: '#1a1a1a'}}
              />
            </Flex>

            <Button
              w="391px"
              justifySelf="start"
              isDisabled={code?.length !== 6}
              withoutLoader
              fontSize="18px"
              fontWeight="400"
              mt={0}
              onClick={() => mutation.mutate({...siginBodyValues})}
            >
              {mutation.isLoading ? <Spinner color="#191919" /> : 'Proceed'}
            </Button>
          </Stack>
        </Box>
      </Stack>
    </div>
  );
};

export default TwoFAForm;
